const fs = require("fs");
const path = require("path");

const sourcePath = path.join(__dirname, "questions.txt");
const outputPath = path.join(__dirname, "questions.js");

function normalizeText(value) {
  return String(value || "")
    .replace(/\uFEFF/g, "")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .trim();
}

function normalizeAnswer(rawAnswer, options, type, id) {
  const raw = String(rawAnswer || "").trim();
  const compact = raw.replace(/\s+/g, "").toUpperCase();

  if (/^[A-Z]+$/.test(compact)) {
    return compact
      .split("")
      .filter((letter, index, arr) => options[letter] && arr.indexOf(letter) === index)
      .sort()
      .join("");
  }

  if (type === "判断题" || raw === "对" || raw === "错") {
    const target = raw.includes("对") ? "对" : raw.includes("错") ? "错" : "";
    const match = Object.entries(options).find(([, text]) => text.trim() === target);
    if (match) return match[0];
  }

  const byText = Object.entries(options).find(([, text]) => text.trim() === raw);
  if (byText) return byText[0];

  throw new Error(`第 ${id} 题答案无法映射到选项：${raw}`);
}

function parseBlock(block, index) {
  const lines = block
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);

  if (!lines.length) return null;

  const header = lines[0];
  const headerMatch = header.match(/^\s*(?:第\s*)?(\d+)(?:\s*题)?[.、．]?\s*(.*)$/);
  if (!headerMatch) {
    throw new Error(`第 ${index + 1} 个题块无法识别题号：${header}`);
  }

  const id = Number(headerMatch[1]);
  let question = headerMatch[2].trim();
  let type = "";
  const typeMatch = question.match(/[（(]\s*(单选题|多选题|判断题)\s*[）)]/);
  if (typeMatch) {
    type = typeMatch[1];
    question = question.replace(typeMatch[0], "").trim();
  }

  const options = {};
  let rawAnswer = "";
  const questionExtraLines = [];

  for (let i = 1; i < lines.length; i += 1) {
    const line = lines[i];
    const optionMatch = line.match(/^([A-Z])\s*[.、．]\s*(.+)$/i);
    const answerMatch = line.match(/^(?:答案|正确答案)\s*[:：]\s*([^\s（(]+).*$/);

    if (optionMatch) {
      options[optionMatch[1].toUpperCase()] = optionMatch[2].trim();
    } else if (answerMatch) {
      rawAnswer = answerMatch[1].trim();
    } else {
      questionExtraLines.push(line);
    }
  }

  if (questionExtraLines.length) {
    question = [question, ...questionExtraLines].filter(Boolean).join("\n");
  }

  const optionCount = Object.keys(options).length;
  if (!question) throw new Error(`第 ${id} 题缺少题干`);
  if (optionCount < 2) throw new Error(`第 ${id} 题选项不足，当前选项数：${optionCount}`);
  if (!rawAnswer) throw new Error(`第 ${id} 题缺少答案行`);

  if (!type) {
    type = optionCount === 2 && Object.values(options).every((item) => ["对", "错"].includes(item))
      ? "判断题"
      : rawAnswer.length > 1
        ? "多选题"
        : "单选题";
  }

  const answer = normalizeAnswer(rawAnswer, options, type, id);
  if (!answer) throw new Error(`第 ${id} 题答案为空或不在选项中：${rawAnswer}`);

  return {
    id,
    type,
    question,
    options,
    answer,
    explanation: "",
  };
}

function parseQuestions(text) {
  const normalized = normalizeText(text);
  const blocks = normalized
    .split(/(?=^\s*(?:\d+[.、．]|第\s*\d+\s*题))/m)
    .map((block) => block.trim())
    .filter(Boolean);

  const questions = [];
  const errors = [];

  blocks.forEach((block, index) => {
    try {
      const question = parseBlock(block, index);
      if (question) questions.push(question);
    } catch (error) {
      const preview = block.split("\n").slice(0, 4).join(" / ");
      errors.push(`${error.message}\n题块预览：${preview}`);
    }
  });

  const ids = new Set();
  questions.forEach((question) => {
    if (ids.has(question.id)) {
      errors.push(`第 ${question.id} 题题号重复`);
    }
    ids.add(question.id);
  });

  questions.sort((a, b) => a.id - b.id);
  return { questions, errors };
}

function main() {
  if (!fs.existsSync(sourcePath)) {
    console.error(`找不到题库源文件：${sourcePath}`);
    process.exit(1);
  }

  const source = fs.readFileSync(sourcePath, "utf8");
  const { questions, errors } = parseQuestions(source);

  if (errors.length) {
    console.error("题库解析失败，请根据以下信息修正 questions.txt：");
    errors.forEach((error, index) => console.error(`\n[${index + 1}] ${error}`));
    process.exit(1);
  }

  const typeCounts = questions.reduce((acc, question) => {
    acc[question.type] = (acc[question.type] || 0) + 1;
    return acc;
  }, {});

  const content = [
    "/* Auto-generated by parser.js. Do not edit manually; update questions.txt and rerun `node parser.js`. */",
    `window.QUESTION_BANK = ${JSON.stringify(questions, null, 2)};`,
    "",
  ].join("\n");

  fs.writeFileSync(outputPath, content, "utf8");
  console.log(`解析完成：${questions.length} 题`);
  console.log(`题型统计：${Object.entries(typeCounts).map(([type, count]) => `${type} ${count}`).join("，")}`);
  console.log(`已生成：${outputPath}`);
}

if (require.main === module) {
  main();
}

module.exports = { parseQuestions };
