/* Auto-generated by parser.js. Do not edit manually; update questions.txt or explanations.json and rerun `node parser.js`. */
window.QUESTION_BANK = [
  {
    "id": 1,
    "type": "单选题",
    "question": "AT89C51单片机由（ ）个16位定时器/计数器。",
    "options": {
      "A": "3路",
      "B": "2路",
      "C": "1路",
      "D": "4路"
    },
    "answer": "B",
    "explanation": "AT89C51内部集成两个16位定时/计数器T0和T1。数据手册的特性列表明确指出芯片带有两路16位定时器/计数器，因此答案选择2路。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "特性列表",
        "trust": "official"
      }
    ]
  },
  {
    "id": 2,
    "type": "单选题",
    "question": "P3.1口的第二功能是（ ）。",
    "options": {
      "A": "INT1外中断1",
      "B": "RXD 串口输入端",
      "C": "INT0外中断0",
      "D": "TXD串口输出端"
    },
    "answer": "D",
    "explanation": "端口功能表明P3.1在第二功能下连接串口发送端TXD，因此P3.1的第二功能是串口输出端。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "端口3替代功能表",
        "trust": "official"
      }
    ]
  },
  {
    "id": 3,
    "type": "单选题",
    "question": "TH0=N>>8的含义是将（ ）保存到TH0中。",
    "options": {
      "A": "N的高八位",
      "B": "N的十位",
      "C": "N的个位",
      "D": "N的低八位"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 4,
    "type": "单选题",
    "question": "动态显示中，利用74HC138实现片选时，必须确保数码管的类型是（）。",
    "options": {
      "A": "共阴极",
      "B": "共阳极"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 5,
    "type": "单选题",
    "question": "双列直插式封装的AT89C51单片机有（）引脚",
    "options": {
      "A": "40",
      "B": "16",
      "C": "20",
      "D": "32"
    },
    "answer": "A",
    "explanation": "AT89C51采用40脚双列直插封装。封装资料列出40-lead PDIP封装尺寸，可知双列直插版本有40个引脚。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "包装信息",
        "trust": "official"
      }
    ]
  },
  {
    "id": 6,
    "type": "单选题",
    "question": "AT89C51单片机定时器T0有（ ）个工作方式。",
    "options": {
      "A": "3",
      "B": "2",
      "C": "1",
      "D": "4"
    },
    "answer": "D",
    "explanation": "Philips硬件手册指出定时/计数器0和1有四种模式(模式0~3)，其中模式3只适用于定时器0，因此T0具有四种工作方式。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Timer/Counters章节",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 7,
    "type": "单选题",
    "question": "外中断0中断服务函数的编号为（ ） 。",
    "options": {
      "A": "3",
      "B": "0",
      "C": "2",
      "D": "1"
    },
    "answer": "B",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 8,
    "type": "单选题",
    "question": "AT89C51单片机在定时器0和外中断0同时申请中断时，CPU首先响应（ ）。",
    "options": {
      "A": "定时器0",
      "B": "外中断0"
    },
    "answer": "B",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 9,
    "type": "单选题",
    "question": "SCON中RI的含义（ ）。",
    "options": {
      "A": "多机通信发送第九位",
      "B": "多机通信接收第九位",
      "C": "接收完毕中断标志",
      "D": "发送完毕中断标志"
    },
    "answer": "C",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 10,
    "type": "单选题",
    "question": "AT89C51单片机可以访问的最大程序存储器空间（ ）。",
    "options": {
      "A": "4KB",
      "B": "64KB",
      "C": "8KB",
      "D": "16KB"
    },
    "answer": "B",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 11,
    "type": "单选题",
    "question": "AT89C51内部提供的T1定时器有（ ）种工作方式。",
    "options": {
      "A": "4",
      "B": "3",
      "C": "1",
      "D": "2"
    },
    "answer": "B",
    "explanation": "硬件说明书描述：定时器1只支持模式0、1、2；模式3仅用于定时器0。因此定时器1有三种工作方式。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Timer/Counters章节",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 12,
    "type": "单选题",
    "question": "P3.0口的第二功能是（ ）。",
    "options": {
      "A": "RXD 串口输入端",
      "B": "INT0外中断0",
      "C": "INT1外中断1",
      "D": "TXD串口输出端"
    },
    "answer": "A",
    "explanation": "端口3替代功能表明P3.0连接串口RXD作为串口输入端，因此其第二功能是串口输入。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "端口3替代功能表",
        "trust": "official"
      }
    ]
  },
  {
    "id": 13,
    "type": "单选题",
    "question": "串行通信中方式2的波特率是（ ）。",
    "options": {
      "A": "晶振频率/32",
      "B": "晶振频率",
      "C": "晶振频率/16",
      "D": "晶振频率/8"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 14,
    "type": "单选题",
    "question": "串口工作在方式1允许接收，则SCON应该取值为（ ）。",
    "options": {
      "A": "0x90",
      "B": "0x50",
      "C": "0x10",
      "D": "0x00"
    },
    "answer": "B",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 15,
    "type": "单选题",
    "question": "12MHz晶振下，定时器在方式1下最大定时时间为（ ）。",
    "options": {
      "A": "16.384ms",
      "B": "0.256ms",
      "C": "8.192ms",
      "D": "65.536ms"
    },
    "answer": "D",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 16,
    "type": "单选题",
    "question": "SCON中用于保存多机通信接收到的第九位信息的是（ ）。",
    "options": {
      "A": "TI",
      "B": "RI",
      "C": "TB8",
      "D": "RB8"
    },
    "answer": "D",
    "explanation": "串口在模式2和模式3传输11位，其中第九位数据由RB8保存。硬件说明指出接收数据的第九位存入SCON寄存器中的RB8，因此用于保存多机通信接收到的第九位信息的是RB8。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "串口模式描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 17,
    "type": "单选题",
    "question": "单片机是将（ ）做到一块集成电路芯片中，称为单片机。",
    "options": {
      "A": "CPU、RAM",
      "B": "CPU、RAM、ROM",
      "C": "CPU、RAM、ROM、I/O设备",
      "D": "CPU、I/O设备"
    },
    "answer": "C",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 18,
    "type": "单选题",
    "question": "74HC595的MR引脚的功能是（）。",
    "options": {
      "A": "移位时钟端",
      "B": "数据输入端",
      "C": "存储器清零端",
      "D": "锁存端"
    },
    "answer": "C",
    "explanation": "74HC595的数据手册指出MR为复位信号，低电平时清空移位寄存器内容，因此其功能是存储器清零。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "74HC595 Serial-in/Serial or Parallel-out 8-bit Shift Register",
        "publisher": "Nexperia",
        "url": "https://assets.nexperia.com/documents/data-sheet/74HC_HCT595.pdf",
        "documentId": "74HC595",
        "locator": "General description",
        "trust": "official"
      }
    ]
  },
  {
    "id": 19,
    "type": "单选题",
    "question": "C51中用（ ）符号表示十六进制数字。",
    "options": {
      "A": "0",
      "B": "B",
      "C": "0X",
      "D": "D"
    },
    "answer": "C",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 20,
    "type": "单选题",
    "question": "TCON中TF0代表的含义是（ ）。",
    "options": {
      "A": "定时器T1启动位",
      "B": "定时器T0溢出位",
      "C": "定时器T1溢出位",
      "D": "定时器T0启动位"
    },
    "answer": "B",
    "explanation": "TCON寄存器中的TF0位是定时器0溢出标志，当T0溢出时硬件置1，因此TF0的含义是定时器T0溢出位。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "TCON寄存器表",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 21,
    "type": "单选题",
    "question": "在MCS-51系统中，若晶振频率为6MHz，一个机器周期等于（ ）μs。",
    "options": {
      "A": "2",
      "B": "3",
      "C": "1",
      "D": "4"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 22,
    "type": "单选题",
    "question": "串行通信中的起始位由（ ）电平表示。",
    "options": {
      "A": "高",
      "B": "不确定",
      "C": "高阻",
      "D": "低"
    },
    "answer": "D",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 23,
    "type": "单选题",
    "question": "AT89C51单片机的可靠复位需要在RST引脚产生（）电平？",
    "options": {
      "A": "高",
      "B": "低"
    },
    "answer": "A",
    "explanation": "数据手册指出RST引脚保持高电平两个机器周期即可复位单片机，复位完成后需将RST拉低才能退出复位。因此可靠复位需要在RST脚产生高电平。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "复位描述",
        "trust": "official"
      }
    ]
  },
  {
    "id": 24,
    "type": "单选题",
    "question": "IE中EA代表的含义是（ ）。",
    "options": {
      "A": "定时器0中断允许",
      "B": "中断允许总控位",
      "C": "定时器1中断允许",
      "D": "串口中断允许"
    },
    "answer": "B",
    "explanation": "待人工复核：IE寄存器的最高位EA是全局中断控制位，EA=1时允许各中断位起作用，EA=0时屏蔽全部中断。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 25,
    "type": "单选题",
    "question": "定时器T0和T1均工作在方式1，则TMOD需要设置为（ ）。",
    "options": {
      "A": "0X01",
      "B": "0XFF",
      "C": "0X11",
      "D": "0X10"
    },
    "answer": "C",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 26,
    "type": "单选题",
    "question": "P3.2口的第二功能是（ ）。",
    "options": {
      "A": "INT1外中断1",
      "B": "串口输出端",
      "C": "RXD 串口输入端",
      "D": "INT0外中断0"
    },
    "answer": "D",
    "explanation": "P3.2的第二功能是INT0外部中断0输入端，数据手册在端口替代功能表中列出P3.2=INT0。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "端口3替代功能表",
        "trust": "official"
      }
    ]
  },
  {
    "id": 27,
    "type": "单选题",
    "question": "已知X的补码为00001000B，则X的真值是十进制（ ）。",
    "options": {
      "A": "-136",
      "B": "-120",
      "C": "8",
      "D": "120"
    },
    "answer": "C",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 28,
    "type": "单选题",
    "question": "SCON中TI的含义（ ）。",
    "options": {
      "A": "多机通信发送第九位",
      "B": "多机通信接收第九位",
      "C": "接收完毕中断标志",
      "D": "发送完毕中断标志"
    },
    "answer": "D",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 29,
    "type": "单选题",
    "question": "AT89C51单片机的（ ）口的引脚，还具有外中断、串行通信等第二功能。",
    "options": {
      "A": "P3",
      "B": "P0",
      "C": "P2",
      "D": "P1"
    },
    "answer": "A",
    "explanation": "P3口的每一个引脚既是普通I/O又兼具串口、外部中断、定时器输入等功能，而其它端口仅用于通用I/O，因此具有第二功能引脚的端口是P3。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "端口功能表",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 30,
    "type": "单选题",
    "question": "AT89C51单片机的工作频率最大为（）",
    "options": {
      "A": "12MHz",
      "B": "48MHz",
      "C": "6MHz",
      "D": "24MHz"
    },
    "answer": "D",
    "explanation": "AT89C51为全静态CMOS设计，手册指出其最大工作频率可达24MHz。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "特性列表",
        "trust": "official"
      }
    ]
  },
  {
    "id": 31,
    "type": "单选题",
    "question": "串行口中断服务函数的编号为（ ） 。",
    "options": {
      "A": "3",
      "B": "2",
      "C": "4",
      "D": "1"
    },
    "answer": "C",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 32,
    "type": "单选题",
    "question": "在16*16点阵显示中，逐行扫描的频率最小为（）Hz？",
    "options": {
      "A": "8*24",
      "B": "32*24",
      "C": "24",
      "D": "16*24"
    },
    "answer": "D",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 33,
    "type": "单选题",
    "question": "要设计一个32键的行列式键盘，至少需要占用（ ）根引脚线。",
    "options": {
      "A": "无法确定",
      "B": "12",
      "C": "18",
      "D": "32"
    },
    "answer": "B",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 34,
    "type": "单选题",
    "question": "AT89C51单片机串口可以工作（ ）模式下。",
    "options": {
      "A": "单工通信",
      "B": "半双工通信",
      "C": "不确定",
      "D": "全双工通信"
    },
    "answer": "D",
    "explanation": "硬件说明书描述串口为全双工，能够同时发送和接收数据，并具有独立的接收缓冲区。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "标准串行接口章节",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 35,
    "type": "单选题",
    "question": "AT89C51单片机对内部脉冲计数实现的是（ ）功能。",
    "options": {
      "A": "计数器",
      "B": "定时器"
    },
    "answer": "B",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 36,
    "type": "单选题",
    "question": "sbit 用于声明（）变量？",
    "options": {
      "A": "字符",
      "B": "特殊功能寄存器的位",
      "C": "实型",
      "D": "整形"
    },
    "answer": "B",
    "explanation": "待人工复核：在C51编程中sbit用于声明特殊功能寄存器的位，例如P0.0、P3.7等，用于直接访问单个位。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 37,
    "type": "单选题",
    "question": "P3.3口的第二功能是（ ）。",
    "options": {
      "A": "INT0外中断0",
      "B": "TXD串口输出端",
      "C": "INT1外中断1",
      "D": "RXD 串口输入端"
    },
    "answer": "C",
    "explanation": "P3.3在端口替代功能表中对应外部中断1输入端(INT1)，因此第二功能为INT1。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "端口3替代功能表",
        "trust": "official"
      }
    ]
  },
  {
    "id": 38,
    "type": "单选题",
    "question": "SCON中SM0，SM1取00代表的含义是串行工作方式（ ）。",
    "options": {
      "A": "工作方式1",
      "B": "工作方式2",
      "C": "工作方式0",
      "D": "工作方式3"
    },
    "answer": "C",
    "explanation": "SCON寄存器的SM0、SM1位选择串口模式，其中00表示模式0(同步移位寄存器方式)。因此SM0,SM1取00即为工作方式0。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "串口模式描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 39,
    "type": "单选题",
    "question": "74HC595的OE引脚的功能是（）。",
    "options": {
      "A": "存储器清零端",
      "B": "输出使能端",
      "C": "锁存端",
      "D": "数据输入端"
    },
    "answer": "B",
    "explanation": "74HC595的OE为输出使能端，OE为低时锁存输出端有效，为高时输出进入高阻。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "74HC595 Serial-in/Serial or Parallel-out 8-bit Shift Register",
        "publisher": "Nexperia",
        "url": "https://assets.nexperia.com/documents/data-sheet/74HC_HCT595.pdf",
        "documentId": "74HC595",
        "locator": "General description",
        "trust": "official"
      }
    ]
  },
  {
    "id": 40,
    "type": "单选题",
    "question": "bit 用于声明（）类型的变量？",
    "options": {
      "A": "实型",
      "B": "字符",
      "C": "整形",
      "D": "位"
    },
    "answer": "D",
    "explanation": "待人工复核：bit类型用于声明位变量，它占用位寻址区中的一个位，可用于表示0或1。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 41,
    "type": "单选题",
    "question": "AT89C51单片机具有第二功能引脚的端口是（ ）。",
    "options": {
      "A": "P1",
      "B": "P2",
      "C": "P0",
      "D": "P3"
    },
    "answer": "D",
    "explanation": "P3端口每个引脚都有第二功能，如串口、定时器输入、写读外部RAM等，其他端口不具备此类功能，因此具有第二功能的端口是P3。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "端口功能表",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 42,
    "type": "单选题",
    "question": "串行通信中的停止位由（ ）电平标示。",
    "options": {
      "A": "高",
      "B": "不确定",
      "C": "低",
      "D": "高阻"
    },
    "answer": "A",
    "explanation": "异步串口帧由起始位(0)、数据位和停止位组成，停止位为1(高电平)，因此停止位由高电平标识。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "串口模式描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 43,
    "type": "单选题",
    "question": "C51中用（ ）符号表示八进制数字。",
    "options": {
      "A": "0X",
      "B": "D",
      "C": "B",
      "D": "O"
    },
    "answer": "D",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 44,
    "type": "单选题",
    "question": "欲使P1口的低4位输出0，高4位不变，应执行一条（ ）命令。",
    "options": {
      "A": "P1&=0X0F",
      "B": "P1&=0XF0",
      "C": "P1=0XF0",
      "D": "P1=0X0F"
    },
    "answer": "B",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 45,
    "type": "单选题",
    "question": "IE中EX0代表的含义是允许（ ）中断。",
    "options": {
      "A": "定时器T0",
      "B": "外中断0",
      "C": "外中断1",
      "D": "定时器T1"
    },
    "answer": "B",
    "explanation": "待人工复核：IE寄存器的位0 (EX0) 用于使能外部中断0，设为1允许外中断0触发。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 46,
    "type": "单选题",
    "question": "外中断1中断服务函数的编号为（ ） 。",
    "options": {
      "A": "4",
      "B": "1",
      "C": "2",
      "D": "3"
    },
    "answer": "C",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 47,
    "type": "单选题",
    "question": "TCON中IE0代表的含义是（ ）。",
    "options": {
      "A": "外中断0请求标志",
      "B": "外中断1触发控制位",
      "C": "外中断0触发控制位",
      "D": "外中断1请求标志"
    },
    "answer": "A",
    "explanation": "TCON寄存器的IE0位是外部中断0的中断请求标志，该位由硬件在检测到触发沿时置1。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "TCON寄存器表",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 48,
    "type": "单选题",
    "question": "串行通信中方式1的功能是（ ）。",
    "options": {
      "A": "固定频率9位通信",
      "B": "同步移位寄存器方式",
      "C": "8位异步通信",
      "D": "可变频率9位通信"
    },
    "answer": "C",
    "explanation": "串口模式1为异步通信，每次传输10位(起始位+8位数据+停止位)，因此称为8位异步通信模式。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "串口模式描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 49,
    "type": "单选题",
    "question": "串行通信中的空闲信号由（ ）电平标示。",
    "options": {
      "A": "低",
      "B": "高阻",
      "C": "不确定",
      "D": "高"
    },
    "answer": "D",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 50,
    "type": "单选题",
    "question": "通常一个16*16点阵汉字需要（）字节保存？",
    "options": {
      "A": "8",
      "B": "64",
      "C": "16",
      "D": "32"
    },
    "answer": "D",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 51,
    "type": "单选题",
    "question": "开启定时器0时TR0的值应该设置为（ ）。",
    "options": {
      "A": "OXFF",
      "B": "0",
      "C": "1",
      "D": "-1"
    },
    "answer": "C",
    "explanation": "TR0是定时器0运行控制位，软件写1启动定时器0，写0停止定时器0。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "TCON寄存器表",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 52,
    "type": "单选题",
    "question": "打开定时器T0和T1中断，需要设置IE为（ ）。",
    "options": {
      "A": "0X8A",
      "B": "0X80",
      "C": "0X82",
      "D": "0X88"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 53,
    "type": "单选题",
    "question": "定时方式1是（ )位二进制定时。",
    "options": {
      "A": "8",
      "B": "13",
      "C": "16",
      "D": "32"
    },
    "answer": "C",
    "explanation": "定时器模式1使用16位计数器，由寄存器THx和TLx组成，最大计数65536，即16位二进制计数。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Timer/Counters模式说明",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 54,
    "type": "单选题",
    "question": "AT89C51单片机有（ ）个端口。",
    "options": {
      "A": "3",
      "B": "1",
      "C": "4",
      "D": "2"
    },
    "answer": "C",
    "explanation": "AT89C51提供32条可编程I/O线，即4个8位端口(P0~P3)，故有4个端口。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "特性列表",
        "trust": "official"
      }
    ]
  },
  {
    "id": 55,
    "type": "单选题",
    "question": "当允许定时器1工作在方式1时，控制字TMOD应为（ ）。",
    "options": {
      "A": "0X01",
      "B": "0XFF",
      "C": "0X11",
      "D": "0X10"
    },
    "answer": "D",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 56,
    "type": "单选题",
    "question": "定时/计数器T1的溢出标志位是（ ）。",
    "options": {
      "A": "IE1",
      "B": "TF1",
      "C": "IT1",
      "D": "ET1"
    },
    "answer": "B",
    "explanation": "TCON寄存器中的TF1是定时器/计数器1溢出标志，当T1溢出时由硬件置位。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "TCON寄存器表",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 57,
    "type": "单选题",
    "question": "串行通信中方式0的功能是（ ）。",
    "options": {
      "A": "可变频率9位通信",
      "B": "固定频率9位通信",
      "C": "同步移位寄存器方式",
      "D": "8位异步通信"
    },
    "answer": "C",
    "explanation": "串口模式0为同步移位寄存器方式，通过RxD串行移位8位数据并由TxD输出移位时钟，是固定速率的同步通信。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "串口模式描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 58,
    "type": "单选题",
    "question": "AT89C51是（ ）位的单片机。",
    "options": {
      "A": "8",
      "B": "32",
      "C": "16",
      "D": "4"
    },
    "answer": "A",
    "explanation": "AT89C51的CPU处理字长为8位，为标准的8位单片机。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "文档标题",
        "trust": "official"
      }
    ]
  },
  {
    "id": 59,
    "type": "单选题",
    "question": "定时器默认的内部时钟源是振荡器信号的（ )分频。",
    "options": {
      "A": "16",
      "B": "4",
      "C": "12",
      "D": "8"
    },
    "answer": "C",
    "explanation": "定时器在计时方式下每个机器周期计数一次。机器周期由十二个振荡周期组成，因此定时器的内部时钟频率是晶振频率的1/12。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Timer/Counters章节",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 60,
    "type": "单选题",
    "question": "在异步通信中若每个字符由10位组成，串行口波特率为4800bps，则每秒传送字符数最多为（ ）。",
    "options": {
      "A": "120",
      "B": "960",
      "C": "480",
      "D": "240"
    },
    "answer": "C",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 61,
    "type": "单选题",
    "question": "开机时，TR0的默认值是（ ）。",
    "options": {
      "A": "OXFF",
      "B": "1",
      "C": "-1",
      "D": "0"
    },
    "answer": "D",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 62,
    "type": "单选题",
    "question": "中断使能寄存器IE中ES代表的含义是（ ）。",
    "options": {
      "A": "中断允许总控位",
      "B": "定时器0中断允许",
      "C": "串口中断允许",
      "D": "定时器1中断允许"
    },
    "answer": "C",
    "explanation": "待人工复核：IE寄存器的ES位为串行口中断允许位，ES=1时启用串口中断，=0时禁止串口中断。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 63,
    "type": "单选题",
    "question": "74HC595的SH_CP引脚的功能是（）。",
    "options": {
      "A": "锁存端",
      "B": "片选信号",
      "C": "移位时钟端",
      "D": "数据输入端"
    },
    "answer": "C",
    "explanation": "SH_CP是74HC595的移位时钟输入端，数据在SH_CP的低到高跃变时移入移位寄存器。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "74HC595 Serial-in/Serial or Parallel-out 8-bit Shift Register",
        "publisher": "Nexperia",
        "url": "https://assets.nexperia.com/documents/data-sheet/74HC_HCT595.pdf",
        "documentId": "74HC595",
        "locator": "General description",
        "trust": "official"
      }
    ]
  },
  {
    "id": 64,
    "type": "单选题",
    "question": "74HC595的ST_CP引脚的功能是（）。",
    "options": {
      "A": "数据输入端",
      "B": "片选信号",
      "C": "锁存端",
      "D": "移位时钟端"
    },
    "answer": "C",
    "explanation": "ST_CP是74HC595的锁存时钟输入，每个上升沿将移位寄存器中的数据锁存到输出缓冲，从而更新输出。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "74HC595 Serial-in/Serial or Parallel-out 8-bit Shift Register",
        "publisher": "Nexperia",
        "url": "https://assets.nexperia.com/documents/data-sheet/74HC_HCT595.pdf",
        "documentId": "74HC595",
        "locator": "General description",
        "trust": "official"
      }
    ]
  },
  {
    "id": 65,
    "type": "单选题",
    "question": "T1中断服务函数的编号为（ ） 。",
    "options": {
      "A": "3",
      "B": "2",
      "C": "1",
      "D": "4"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 66,
    "type": "单选题",
    "question": "AT89C51单片机定时器采用的是（ ）计数方式。",
    "options": {
      "A": "不确定",
      "B": "减计数",
      "C": "加或减计数",
      "D": "加计数"
    },
    "answer": "D",
    "explanation": "定时器工作在定时模式时由内部时钟驱动向上计数，没有减计数功能，因此采用加计数方式。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Timer/Counters章节",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 67,
    "type": "单选题",
    "question": "若振荡频率为12MHz，在方式2下最大定时时间为（ ）。",
    "options": {
      "A": "65.536ms",
      "B": "8.192ms",
      "C": "16.384ms",
      "D": "0.256ms"
    },
    "answer": "D",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 68,
    "type": "单选题",
    "question": "控制串形接口工作方式的寄存器是（ ）。",
    "options": {
      "A": "PCON",
      "B": "TMOD",
      "C": "TCON",
      "D": "SCON"
    },
    "answer": "D",
    "explanation": "串口工作方式由SCON寄存器的SM0、SM1等位控制，因此串形接口模式由SCON寄存器设定。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "串口模式描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 69,
    "type": "单选题",
    "question": "串行通信中方式2的功能是（ ）。",
    "options": {
      "A": "固定频率9位通信",
      "B": "8位异步通信",
      "C": "可变频率9位通信",
      "D": "同步移位寄存器方式"
    },
    "answer": "A",
    "explanation": "模式2传输11位数据，其中包括可编程的第九位数据位和固定起始/停止位；文档指出其波特率是晶振频率的1/32或1/64，属于固定频率9位通信。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "模式2描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 70,
    "type": "单选题",
    "question": "ADC0809的转换速率主要取决于（）。",
    "options": {
      "A": "启动信号",
      "B": "参考电压",
      "C": "供电电压",
      "D": "工作频率的大小"
    },
    "answer": "D",
    "explanation": "ADC0809的转换速率由时钟信号决定。TI公司数据手册指出典型转换时间在640kHz时钟下为100μs，时钟频率越高转换越快，因此转换速率主要取决于工作频率。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "ADC0808/ADC0809 8-Bit A/D Converters",
        "publisher": "Texas Instruments",
        "url": "https://www.ti.com/lit/ds/symlink/adc0808-n.pdf",
        "documentId": "ADC0809",
        "locator": "特性描述",
        "trust": "official"
      }
    ]
  },
  {
    "id": 71,
    "type": "单选题",
    "question": "下面（ ）种方式适合用于处理外部突发事件。",
    "options": {
      "A": "DMA",
      "B": "条件查询传送",
      "C": "中断",
      "D": "无条件传送"
    },
    "answer": "C",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 72,
    "type": "单选题",
    "question": "74HC138的A、B、C引脚的作用是（）。",
    "options": {
      "A": "使能",
      "B": "复位",
      "C": "改变输出引脚的状态"
    },
    "answer": "C",
    "explanation": "74HC138是3线至8线译码器，地址输入A、B、C决定哪一个输出为低电平，从而改变输出状态。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "74HC138 3-to-8 line decoder",
        "publisher": "On Semiconductor",
        "url": "https://www.onsemi.com/pdf/datasheet/mc74hc138a-d.pdf",
        "documentId": "74HC138",
        "locator": "General description",
        "trust": "official"
      }
    ]
  },
  {
    "id": 73,
    "type": "单选题",
    "question": "AT89C51单片机串口的工作方式有（ ）种。",
    "options": {
      "A": "2",
      "B": "3",
      "C": "1",
      "D": "4"
    },
    "answer": "D",
    "explanation": "手册列出串口有四种工作方式：模式0(移位寄存器)、模式1(8位异步)、模式2(固定9位)和模式3(可变9位)，因此共有四种。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "串口模式描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 74,
    "type": "单选题",
    "question": "1个16*16点阵可以由（）个8*8点阵实现？",
    "options": {
      "A": "3",
      "B": "4",
      "C": "1",
      "D": "2"
    },
    "answer": "B",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 75,
    "type": "单选题",
    "question": "SCON中SM2用于方式（ ）。",
    "options": {
      "A": "工作方式1",
      "B": "仅在工作方式3中",
      "C": "工作方式2和3",
      "D": "工作方式0"
    },
    "answer": "C",
    "explanation": "SM2位用于多机通信功能。手册指出在模式2和模式3中，当SM2置1时只有接收到的第九位为1时才产生串口中断，从而区分地址和数据帧，因此SM2用于模式2和模式3。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Multiprocessor Communications",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 76,
    "type": "单选题",
    "question": "串行通信中方式3的功能是（ ）。",
    "options": {
      "A": "可变频率9位通信",
      "B": "8位异步通信",
      "C": "同步移位寄存器方式",
      "D": "固定频率9位通信"
    },
    "answer": "A",
    "explanation": "模式3与模式2相同也是9位通信，但模式3的波特率由定时器产生可变，因此属于可变频率9位通信。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "模式3描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 77,
    "type": "单选题",
    "question": "74HC595的DS引脚的功能是（）。",
    "options": {
      "A": "移位时钟端",
      "B": "片选信号",
      "C": "数据输入端",
      "D": "锁存端"
    },
    "answer": "C",
    "explanation": "74HC595的DS引脚是串行数据输入端，串行数据从此端输入移位寄存器。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "74HC595 Serial-in/Serial or Parallel-out 8-bit Shift Register",
        "publisher": "Nexperia",
        "url": "https://assets.nexperia.com/documents/data-sheet/74HC_HCT595.pdf",
        "documentId": "74HC595",
        "locator": "General description",
        "trust": "official"
      }
    ]
  },
  {
    "id": 78,
    "type": "单选题",
    "question": "IE中EX1代表的含义是允许（ ）中断。",
    "options": {
      "A": "定时器T1",
      "B": "定时器T0",
      "C": "外中断1",
      "D": "外冲断0"
    },
    "answer": "C",
    "explanation": "待人工复核：IE寄存器的EX1位是外中断1允许位，EX1=1时允许INT1产生中断，=0时禁止。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 79,
    "type": "单选题",
    "question": "CPU又称为（）",
    "options": {
      "A": "控制器",
      "B": "输入/输出设备",
      "C": "运算器",
      "D": "中央处理器"
    },
    "answer": "D",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 80,
    "type": "单选题",
    "question": "AT89C51复位时,下述说法正确的是（ ）。",
    "options": {
      "A": "SP=00H",
      "B": "P0=00H",
      "C": "SBUF=00H",
      "D": "TH0=00H"
    },
    "answer": "D",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 81,
    "type": "单选题",
    "question": "当采用12MHz晶振时，定时器的工作时钟周期为（）μs。",
    "options": {
      "A": "0.5",
      "B": "2",
      "C": "1",
      "D": "3"
    },
    "answer": "C",
    "explanation": "晶振频率为12MHz时，机器周期为12个振荡周期，即1μs，因此定时器的工作时钟周期为1μs。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Timer/Counters章节",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 82,
    "type": "单选题",
    "question": "设计一个16键的矩阵式键盘，至少需要占用（ ）IO引脚。",
    "options": {
      "A": "2",
      "B": "6",
      "C": "8",
      "D": "4"
    },
    "answer": "C",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 83,
    "type": "多选题",
    "question": "电子时钟项目中包括（）模块",
    "options": {
      "A": "数码管显示模块",
      "B": "按键",
      "C": "点阵模块",
      "D": "74595"
    },
    "answer": "ABD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 84,
    "type": "多选题",
    "question": "一般常用（）显示字符点阵，而用（）显示汉字点阵",
    "options": {
      "A": "32*32",
      "B": "16*16",
      "C": "8*8"
    },
    "answer": "BC",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 85,
    "type": "多选题",
    "question": "A/D转换后的结果可以采用（）方法采集。",
    "options": {
      "A": "查询",
      "B": "中断",
      "C": "延时"
    },
    "answer": "ABC",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 86,
    "type": "多选题",
    "question": "定时器/计数器T1有（ ）3种工作方式。",
    "options": {
      "A": "方式3",
      "B": "方式0",
      "C": "方式1",
      "D": "方式2"
    },
    "answer": "BCD",
    "explanation": "定时器/计数器1支持模式0(13位)、模式1(16位)和模式2(8位自动重载)三种工作方式，模式3仅对定时器0有效。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Timer/Counters模式说明",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 87,
    "type": "多选题",
    "question": "AT89C51单片机最小系统包括（）",
    "options": {
      "A": "电源电路",
      "B": "数码管显示电路",
      "C": "时钟电路",
      "D": "复位电路"
    },
    "answer": "ACD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 88,
    "type": "多选题",
    "question": "超声波身高检测系统中包括（）模块",
    "options": {
      "A": "语音模块",
      "B": "矩阵式按键",
      "C": "串行口通信",
      "D": "超声波模块"
    },
    "answer": "ACD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 89,
    "type": "多选题",
    "question": "数码管按照公共端的不同可以分为（）类型",
    "options": {
      "A": "共阴极",
      "B": "动态显示",
      "C": "静态显示",
      "D": "共阳极"
    },
    "answer": "AD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 90,
    "type": "多选题",
    "question": "利用单片机实现电子琴的设计时，可采用（）来发声",
    "options": {
      "A": "麦克风",
      "B": "有源蜂鸣器",
      "C": "扬声器",
      "D": "无源蜂鸣器"
    },
    "answer": "CD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 91,
    "type": "多选题",
    "question": "利用定时器可以实现（）功能",
    "options": {
      "A": "产生方波",
      "B": "计数",
      "C": "延时",
      "D": "定时"
    },
    "answer": "ABCD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 92,
    "type": "多选题",
    "question": "驱动数码管动态显示的芯片可以采用（）",
    "options": {
      "A": "74595",
      "B": "74161",
      "C": "7447",
      "D": "74138"
    },
    "answer": "ACD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 93,
    "type": "多选题",
    "question": "AT89C51的并行端口作输入口时，必须先写（ ） 才能读入外设的状态。",
    "options": {
      "A": "0",
      "B": "低电平",
      "C": "1",
      "D": "高电平"
    },
    "answer": "CD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 94,
    "type": "多选题",
    "question": "能够触发定时中断的信号有（）",
    "options": {
      "A": "TF1",
      "B": "TI",
      "C": "TF0",
      "D": "RI"
    },
    "answer": "AC",
    "explanation": "定时器中断由定时器溢出标志TF0和TF1产生；当定时器0或1溢出时，TCON中的TF0/TF1位被硬件置位并可触发中断。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "TCON寄存器表",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 95,
    "type": "多选题",
    "question": "关于ADC0809的描述正确的是（）",
    "options": {
      "A": "8个输出输出端",
      "B": "3个通道选择端",
      "C": "8个数据输入端",
      "D": "1个频率信号输入端"
    },
    "answer": "ABCD",
    "explanation": "ADC0809内含一个8位A/D转换器，具有8个模拟输入通道和8个数字输出端；通过3个地址输入选择所需通道，同时需要一个时钟输入控制转换。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "ADC0808/ADC0809 8-Bit A/D Converters",
        "publisher": "Texas Instruments",
        "url": "https://www.ti.com/lit/ds/symlink/adc0808-n.pdf",
        "documentId": "ADC0809",
        "locator": "特性描述",
        "trust": "official"
      },
      {
        "title": "ADC0808/ADC0809 8-Bit A/D Converters",
        "publisher": "Texas Instruments",
        "url": "https://www.ti.com/lit/ds/symlink/adc0808-n.pdf",
        "documentId": "ADC0809",
        "locator": "功能描述",
        "trust": "official"
      }
    ]
  },
  {
    "id": 96,
    "type": "多选题",
    "question": "在工程设计中，定时器T0常用作（），定时T1常用作（）。",
    "options": {
      "A": "定时",
      "B": "计数",
      "C": "延时",
      "D": "波特率发生"
    },
    "answer": "AD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 97,
    "type": "多选题",
    "question": "能够触发串行口中断的信号包括（）",
    "options": {
      "A": "EX0",
      "B": "TI",
      "C": "EX1",
      "D": "RI"
    },
    "answer": "BD",
    "explanation": "待人工复核：串口中断由发送完毕标志TI和接收完毕标志RI触发，任意一个标志置1都会产生串口中断。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 98,
    "type": "多选题",
    "question": "AT89C51的堆栈存取数据的原则是（ ）。",
    "options": {
      "A": "先进后出",
      "B": "后进先出",
      "C": "先进先出",
      "D": "后进后出"
    },
    "answer": "AB",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 99,
    "type": "多选题",
    "question": "AT89C51单片机的中断源分别有外部中断0（ ）。",
    "options": {
      "A": "T1",
      "B": "外部中断1",
      "C": "串行口",
      "D": "T0"
    },
    "answer": "ABCD",
    "explanation": "待人工复核：8051共有五个中断源：外中断0、定时器0、外中断1、定时器1和串口中断；题目列出的四个选项正是这五个中断源的组成。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 100,
    "type": "多选题",
    "question": "虽然ADC0809有（）数据输入端，但是某一刻只有（）引脚起作用",
    "options": {
      "A": "4",
      "B": "1",
      "C": "2",
      "D": "8"
    },
    "answer": "BD",
    "explanation": "ADC0809具有8个模拟输入端，但在任何时刻只有一个通道通过内部多路复用器连接到A/D转换器转换为数字输出。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "ADC0808/ADC0809 8-Bit A/D Converters",
        "publisher": "Texas Instruments",
        "url": "https://www.ti.com/lit/ds/symlink/adc0808-n.pdf",
        "documentId": "ADC0809",
        "locator": "功能描述",
        "trust": "official"
      }
    ]
  },
  {
    "id": 101,
    "type": "多选题",
    "question": "常用的延时方法包括（）",
    "options": {
      "A": "定时器延时",
      "B": "软件延时"
    },
    "answer": "AB",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 102,
    "type": "多选题",
    "question": "独立按键扫描方法包括（）",
    "options": {
      "A": "反转法",
      "B": "扫描法",
      "C": "延时等待法",
      "D": "键标志法"
    },
    "answer": "CD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 103,
    "type": "多选题",
    "question": "常见的波特率包括（）",
    "options": {
      "A": "2400",
      "B": "1200",
      "C": "4800",
      "D": "9600"
    },
    "answer": "ABCD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 104,
    "type": "多选题",
    "question": "AT89C51单片机可以处理的中断包括（）",
    "options": {
      "A": "外中断",
      "B": "串行口中断",
      "C": "看门狗中断",
      "D": "定时器中断"
    },
    "answer": "ABD",
    "explanation": "待人工复核：AT89C51支持外部中断、定时器中断和串口中断，手册未给出看门狗中断，因此题目列出的外中断、串口中断和定时器中断正确。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 105,
    "type": "多选题",
    "question": "与状态相关参数有（）。",
    "options": {
      "A": "触发信号",
      "B": "响应信号",
      "C": "状态圆圈",
      "D": "状态转移线"
    },
    "answer": "ABCD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 106,
    "type": "多选题",
    "question": "单片机控制系统中，常见的按键包括（）",
    "options": {
      "A": "矩阵式按键",
      "B": "轻触开关",
      "C": "旋钮开关",
      "D": "拨码开关"
    },
    "answer": "ABCD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 107,
    "type": "多选题",
    "question": "无源蜂鸣器的特点是（）",
    "options": {
      "A": "两个引脚长度相同",
      "B": "外加电源后还需要加音源才能发声",
      "C": "外加电源后可直接发声",
      "D": "两个引脚长度不同"
    },
    "answer": "AB",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 108,
    "type": "多选题",
    "question": "计算器项目中包括（）模块",
    "options": {
      "A": "超声波模块",
      "B": "数码管",
      "C": "单片机",
      "D": "按键"
    },
    "answer": "BCD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 109,
    "type": "多选题",
    "question": "串行通信的数据传送方式可以是（ ）。",
    "options": {
      "A": "全双工",
      "B": "双工",
      "C": "半双工",
      "D": "单工"
    },
    "answer": "ACD",
    "explanation": "串行通信按传输方向可分为单工、半双工和全双工三种；其中半双工表示双向但不能同时传输，全双工可以同时发送与接收。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "串口描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 110,
    "type": "多选题",
    "question": "按键在与IO相连时一般需要连接（）电阻",
    "options": {
      "A": "下拉",
      "B": "限流",
      "C": "上拉"
    },
    "answer": "AC",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 111,
    "type": "多选题",
    "question": "可利用串行口进行通信的设备包括（）",
    "options": {
      "A": "语音模块",
      "B": "超声波模块",
      "C": "GPS模块",
      "D": "GSM模块"
    },
    "answer": "ABCD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 112,
    "type": "多选题",
    "question": "异步串行数据通信的帧格式一般由（ ）组成。",
    "options": {
      "A": "停止位",
      "B": "校验位",
      "C": "起始位",
      "D": "数据位"
    },
    "answer": "ABCD",
    "explanation": "异步串行数据帧由起始位(0)、数位若干、可选校验位和停止位(1)组成，这些字段构成完整帧格式。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "串口模式描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 113,
    "type": "多选题",
    "question": "AT89C51单片机的外中断触发方式控制位包括（ ）。",
    "options": {
      "A": "IT0",
      "B": "IE0",
      "C": "TI1",
      "D": "IE1"
    },
    "answer": "AC",
    "explanation": "外部中断的触发方式由TCON寄存器中IT0和IT1控制，这两个位选择低电平触发(0)或下降沿触发(1)。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "TCON寄存器表",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 114,
    "type": "多选题",
    "question": "与定时器相关的寄存器包括（）",
    "options": {
      "A": "TRx",
      "B": "TCON",
      "C": "IE",
      "D": "TMOD"
    },
    "answer": "ABCD",
    "explanation": "定时器的工作涉及多种寄存器：TMOD用于设置模式，TCON包含启动和溢出标志，TRx位控制启动/停止，IE寄存器用于使能定时器中断。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Timer/Counters章节",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 115,
    "type": "多选题",
    "question": "计算机中常用于表达数值的码制有（ ）。",
    "options": {
      "A": "反码",
      "B": "原码",
      "C": "补码"
    },
    "answer": "ABC",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 116,
    "type": "多选题",
    "question": "74hc595可以用于驱动（）",
    "options": {
      "A": "蜂鸣器",
      "B": "点阵",
      "C": "继电器",
      "D": "数码管"
    },
    "answer": "BD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 117,
    "type": "多选题",
    "question": "合法的中断服务函数的编号为（ ） 。",
    "options": {
      "A": "2",
      "B": "3",
      "C": "1",
      "D": "0"
    },
    "answer": "ABCD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 118,
    "type": "多选题",
    "question": "常用的数码管显示方式包括（）",
    "options": {
      "A": "动态显示",
      "B": "静态显示",
      "C": "动静结合"
    },
    "answer": "AB",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 119,
    "type": "多选题",
    "question": "中断控制器（）中，EA代表的是开总中断，ET0代表（），EX0代表（）",
    "options": {
      "A": "外中断0允许",
      "B": "IE",
      "C": "定时器0中断允许",
      "D": "定时器1中断允许"
    },
    "answer": "ABC",
    "explanation": "待人工复核：在IE寄存器中，EA是总中断允许位，ET0是定时器0中断允许位，EX0是外中断0允许位，题目所列正是这些含义。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 120,
    "type": "多选题",
    "question": "串行口方式0又称为（）方式，方式1称为（）方式，方式2-3称为（）方式",
    "options": {
      "A": "异步通信",
      "B": "移位寄存器",
      "C": "双机通信",
      "D": "多机通信"
    },
    "answer": "BCD",
    "explanation": "串口模式0为移位寄存器方式(同步通信)，模式1为异步通信，模式2/3用于多机通信(具有可编程的第九位)。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "串口模式描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 121,
    "type": "多选题",
    "question": "AT89C51一直维持复位状态，直到RST脚收到（ ）电平，MCS-51才脱离复位状态，进入程序运行状态。",
    "options": {
      "A": "0",
      "B": "低",
      "C": "1",
      "D": "高"
    },
    "answer": "AB",
    "explanation": "单片机复位时RST保持高电平，在释放复位时必须拉低RST脚才能进入正常执行状态，因此题目中\"0\"或\"低\"表示RST回到低电平。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "复位描述",
        "trust": "official"
      }
    ]
  },
  {
    "id": 122,
    "type": "多选题",
    "question": "AT89C51内部提供的T0定时器有（ ）种工作方式。",
    "options": {
      "A": "方式0",
      "B": "方式3",
      "C": "方式2",
      "D": "方式1"
    },
    "answer": "ABCD",
    "explanation": "T0支持模式0、1、2、3四种工作方式，分别为13位、16位、8位自动重载和分离计数器模式。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Timer/Counters模式说明",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 123,
    "type": "多选题",
    "question": "下列属于输出设备的是（）",
    "options": {
      "A": "继电器",
      "B": "矩阵式按键",
      "C": "蜂鸣器",
      "D": "可控硅"
    },
    "answer": "ACD",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 124,
    "type": "多选题",
    "question": "矩阵式按键主要应用场合是（）",
    "options": {
      "A": "按键少",
      "B": "IO口资源紧张",
      "C": "按键较多",
      "D": "IO口资源丰富"
    },
    "answer": "BC",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 125,
    "type": "多选题",
    "question": "AT89C51单片机的内部硬件结构包括（ ）。",
    "options": {
      "A": "中断控制系统",
      "B": "ROM",
      "C": "定时器",
      "D": "串行口"
    },
    "answer": "ABCD",
    "explanation": "AT89C51内部包括中断控制系统、程序存储器(Flash/ROM)、两个定时器/计数器和一个全双工串行口等硬件模块。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "特性列表",
        "trust": "official"
      }
    ]
  },
  {
    "id": 126,
    "type": "判断题",
    "question": "有源蜂鸣器的两个引脚是等长的。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 127,
    "type": "判断题",
    "question": "串行口收发数据缓存器的名字为SBUF。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "手册指出SBUF是串行口收发缓冲寄存器，实际由发送缓冲和接收缓冲两部分组成。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Serial Data Buffer段",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 128,
    "type": "判断题",
    "question": "AT89C51单片机的外中断常工作在下降沿触发模式下。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 129,
    "type": "判断题",
    "question": "TCON中TF1代表的含义是定时器溢出标志。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "TCON寄存器中的TF1是定时器1溢出标志，在定时器溢出时由硬件置位，这是定时器溢出的标记。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "TCON寄存器表",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 130,
    "type": "判断题",
    "question": "串行口的方式0也称为移位寄存器方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "串口模式0的数据经移位寄存器同步传输，因此又称为移位寄存器方式。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "模式0描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 131,
    "type": "判断题",
    "question": "在串行通信中,数据传送方向单工、半双工、全双工三种方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "串行通信按照数据方向分为单工、半双工和全双工三种，因此题目表述正确。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "串口描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 132,
    "type": "判断题",
    "question": "串行口发生中断时RI或TI至少有一个为1态。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "待人工复核：串口中断请求发生时，RI和TI至少有一个被置1；RI表示接收完成，TI表示发送完成，任意一个为1都会使硬件设置串口中断标志。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 133,
    "type": "判断题",
    "question": "开启定时器T0中断时，应设置IE=0X02。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "待人工复核：启用定时器0中断不能只设置ET0，还必须设置总中断允许位EA。因此IE=0x02仅设置ET0而EA=0，不能开启中断，故题目错误。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 134,
    "type": "判断题",
    "question": "AT89C51中断优先级由寄存器IP来决定。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "待人工复核：中断优先级由IP寄存器设置，IP位为1的中断优先级高于为0的中断。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 135,
    "type": "判断题",
    "question": "开机复位后，每个端口的状态为0。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 136,
    "type": "判断题",
    "question": "有源蜂鸣器的引脚的极性为长正短负。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 137,
    "type": "判断题",
    "question": "中断服务函数中 interrupt 1指的是T0中断的服务函数。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 138,
    "type": "判断题",
    "question": "外部中断1的中断触发标志位是IT0。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "TCON中的IT1是外部中断1触发方式控制位，IE1才是外部中断1的请求标志。题目所述\"外部中断1的中断触发标志位是IT0\"显然错误。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "TCON寄存器表",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 139,
    "type": "判断题",
    "question": "超声波模块可以工作在串行口模式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 140,
    "type": "判断题",
    "question": "外部中断1的输入引脚是P3.2。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "P3.2是外部中断0输入端，P3.3才是外部中断1输入端，所以题目中说外部中断1输入引脚是P3.2是错误的。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "端口3替代功能表",
        "trust": "official"
      }
    ]
  },
  {
    "id": 141,
    "type": "判断题",
    "question": "定时器T1还可以用作串行口波特率发生器使用。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "定时器1常用作串口波特率发生器，特别是在模式2(8位自动重载)下可产生波特率，因此题目正确。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Timer/Counters模式说明",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 142,
    "type": "判断题",
    "question": "启动定时器T0应该使用TR0=1。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "启动定时器T0需要将TR0位置1；当TR0=1时计数器开始计数，TR0=0时停止。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "TCON寄存器表",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 143,
    "type": "判断题",
    "question": "无源蜂鸣器的两个引脚是等长的。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 144,
    "type": "判断题",
    "question": "独立按键识别时，先延时再判断的目的是避开按键抖动。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 145,
    "type": "判断题",
    "question": "AT89C51内部提供2个可编程的16位定时/计数器，T0定时器有3种工作方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "AT89C51内部有两个16位定时/计数器，T0有四种模式而非三种，因此题目说T0只有3种工作方式是错误的。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Timer/Counters模式说明",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 146,
    "type": "判断题",
    "question": "ADC0809内部有8个电压转换模块。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "ADC0809只有一个8位A/D转换器，它通过内部8路模拟多路复用器选择输入通道，故不存在8个独立的电压转换模块，因此题目错误。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "ADC0808/ADC0809 8-Bit A/D Converters",
        "publisher": "Texas Instruments",
        "url": "https://www.ti.com/lit/ds/symlink/adc0808-n.pdf",
        "documentId": "ADC0809",
        "locator": "特性描述",
        "trust": "official"
      }
    ]
  },
  {
    "id": 147,
    "type": "判断题",
    "question": "P3.3的第二功能为外中断1的输入端。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "端口3的P3.3引脚在替代功能中对应外部中断1输入端INT1，因此题目正确。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "端口3替代功能表",
        "trust": "official"
      }
    ]
  },
  {
    "id": 148,
    "type": "判断题",
    "question": "IE中ET1的含义为允许定时器1中断。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "待人工复核：IE寄存器中的ET1位用于允许定时器1中断，ET1=1时T1溢出会产生中断，题目正确。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 149,
    "type": "判断题",
    "question": "MCS-51单片机的外中断可以工作在低电平触发或者下降沿触发模式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "外部中断可配置为低电平触发或下降沿触发；TCON寄存器中的IT0和IT1位决定触发方式，0代表低电平触发，1代表下降沿触发。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "TCON寄存器表",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 150,
    "type": "判断题",
    "question": "P3.2的第二功能为外中断0的输入端。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "P3.2的替代功能是外部中断0输入端INT0，因此题目正确。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "端口3替代功能表",
        "trust": "official"
      }
    ]
  },
  {
    "id": 151,
    "type": "判断题",
    "question": "若使用T0中断，则只需要设置ET0=1即可。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "待人工复核：打开T0中断时不仅要设置ET0=1，还要将EA=1，所以仅设置ET0不足以启用中断，题目错误。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 152,
    "type": "判断题",
    "question": "串行口中断结束后RI由硬件自动清零。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 153,
    "type": "判断题",
    "question": "74HC595芯片的功能是数据锁存。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "74HC595是串行输入/并行输出移位寄存器，其输出通过OE控制门控并带有锁存功能，但其主要作用是移位和锁存而不只是存储。题目说它仅用于数据锁存是不全面的。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "74HC595 Serial-in/Serial or Parallel-out 8-bit Shift Register",
        "publisher": "Nexperia",
        "url": "https://assets.nexperia.com/documents/data-sheet/74HC_HCT595.pdf",
        "documentId": "74HC595",
        "locator": "General description",
        "trust": "official"
      }
    ]
  },
  {
    "id": 154,
    "type": "判断题",
    "question": "8位有符号数的范围为-128~127。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "待人工复核：有符号8位整数范围是−128到+127。C51编程文档给出了signed char类型的范围为−128到+127。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 155,
    "type": "判断题",
    "question": "AT89C51的中断源全部编程为同级时，优先级最低的是外中断0。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "待人工复核：当所有中断优先级相同（默认）时，外部中断0优先级最高，串口中断优先级最低，题目说外中断0最低优先级是不正确的。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 156,
    "type": "判断题",
    "question": "定时器T0工作在方式1下，采用定时功能，门控位不使用，则TMOD=1。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 157,
    "type": "判断题",
    "question": "ADC0809的转换精度为参考电压Vref/256。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "ADC0809是8位转换器，输出分辨率为256个数字级，因此电压分辨率等于参考电压除以256。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "ADC0808/ADC0809 8-Bit A/D Converters",
        "publisher": "Texas Instruments",
        "url": "https://www.ti.com/lit/ds/symlink/adc0808-n.pdf",
        "documentId": "ADC0809",
        "locator": "特性描述",
        "trust": "official"
      }
    ]
  },
  {
    "id": 158,
    "type": "判断题",
    "question": "LED常采用灌电流的驱动方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 159,
    "type": "判断题",
    "question": "外部中断1的中断请求标志位是TF1。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "外部中断1的中断请求标志是IE1，而TF1是定时器1溢出标志，二者不同，因此题目错误。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "TCON寄存器表",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 160,
    "type": "判断题",
    "question": "IP的默认值为0。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 161,
    "type": "判断题",
    "question": "IT1=1表示外部中断1的触发方式为边沿触发。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "TCON寄存器的IT1位为外部中断1触发方式控制位，当IT1=1时表示下降沿触发，因此题目说IT1=1表示边沿触发正确。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "TCON寄存器表",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 162,
    "type": "判断题",
    "question": "矩阵式按键扫描常用的方法有翻转法和扫描法。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 163,
    "type": "判断题",
    "question": "MCS-51内部有4个并行IO口。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "MCS-51芯片有四个8位并行I/O端口，共32条I/O线，因此说内部有4个并行口是正确的。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "特性列表",
        "trust": "official"
      }
    ]
  },
  {
    "id": 164,
    "type": "判断题",
    "question": "数码管动态显示利用了视觉暂留效应。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 165,
    "type": "判断题",
    "question": "SCON中SM0,SM1取01代表的含义是串行工作方式1。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "SCON寄存器的SM0=0、SM1=1配置串口为模式1(8位异步通信)，因此SM0,SM1取01即为串行工作方式1。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "模式1描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 166,
    "type": "判断题",
    "question": "定时器T1的方式1常用于串行口波特率发生器使用。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "串口波特率发生器通常使用定时器1的模式2(8位自动重载)，而非模式1，因此说定时器1模式1常用于波特率发生器是不正确的。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Timer/Counters模式说明",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 167,
    "type": "判断题",
    "question": "无符号字节型变量的表达范围是0~255。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "待人工复核：无符号字节型(unsigned char)取值范围是0~255，C51编程资料中给出了这一范围。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 168,
    "type": "判断题",
    "question": "CPU的运算器可以完成算数运算和逻辑运算。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 169,
    "type": "判断题",
    "question": "89的补码用8位二进制数表示是01011001B。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 170,
    "type": "判断题",
    "question": "SM2用于多机通信方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "SM2用于多机通信功能。在模式2和3中，SM2=1时仅当第九位为1(地址帧)才触发串口中断，实现多机通信。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Multiprocessor Communications",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 171,
    "type": "判断题",
    "question": "AT89C51有5个中断源。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "待人工复核：标准8051有5个中断源：外中断0、定时器0、外中断1、定时器1和串口中断。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 172,
    "type": "判断题",
    "question": "MCS-51单片机的CPU是8位的。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "MCS-51系列CPU宽度为8位，所以AT89C51是8位单片机。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "文档标题",
        "trust": "official"
      }
    ]
  },
  {
    "id": 173,
    "type": "判断题",
    "question": "串行口的方式2和3为多机通信波特率可变的方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "模式2的波特率固定为fOSC/32或fOSC/64，模式3的波特率可变；因此说\"方式2和3为多机通信波特率可变方式\"不准确，只有模式3波特率可变。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "模式2/3描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 174,
    "type": "判断题",
    "question": "设置串口的波特率加倍，则SMOD需要设置为1。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 175,
    "type": "判断题",
    "question": "复位后TMOD的状态为0。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 176,
    "type": "判断题",
    "question": "ADC0809的参考电压可以与单片机的电源电压不同。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "ADC0809的模拟参考电压(VREF)可以独立设置，与单片机的数字供电电压不必相同，因此两者可以不同。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "ADC0808/ADC0809 8-Bit A/D Converters",
        "publisher": "Texas Instruments",
        "url": "https://www.ti.com/lit/ds/symlink/adc0808-n.pdf",
        "documentId": "ADC0809",
        "locator": "特性描述",
        "trust": "official"
      }
    ]
  },
  {
    "id": 177,
    "type": "判断题",
    "question": "串行通信中，RI用于表达数据传输是否结束。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "待人工复核：RI是接收中断标志，表示接收完毕，不能表示发送结束；发送结束标志是TI，因此题目错误。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 178,
    "type": "判断题",
    "question": "定时/计数器T0的中断编号是3。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "待人工复核：定时/计数器T0中断向量地址是000BH，对应的中断编号在Keil C中为1(Interrupt 1)，因此中断编号不是3。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 179,
    "type": "判断题",
    "question": "TMOD是中断允许寄存器。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "TMOD是定时/计数器模式寄存器，用于设置定时器的工作方式；中断允许寄存器是IE，因此题目错误。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Timer/Counters章节",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 180,
    "type": "判断题",
    "question": "AT89C51单片机的串行口有4种工作方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "串行口共有四种工作方式(模式0到模式3)，题目说四种工作方式正确。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "串口模式描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 181,
    "type": "判断题",
    "question": "外部中断0的输入引脚是P3.2。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "P3.2作为外部中断0输入端(INT0)，因此题目正确。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "AT89C51 8-bit Microcontroller with 4K Bytes Flash",
        "publisher": "Microchip",
        "url": "https://ww1.microchip.com/downloads/en/devicedoc/doc0265.pdf",
        "documentId": "doc0265",
        "locator": "端口3替代功能表",
        "trust": "official"
      }
    ]
  },
  {
    "id": 182,
    "type": "判断题",
    "question": "SMOD位于PCON的最高位。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 183,
    "type": "判断题",
    "question": "计算机中补码常用于表达有符号数。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "待人工复核：在计算机中，补码常用于表示有符号整数，因为补码编码使加减运算统一。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 184,
    "type": "判断题",
    "question": "AT89C51单片机定时器采用的是减计数方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "定时器在定时模式下向上计数，而非向下计数；手册明确说明计数器在每个机器周期递增。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "Timer/Counters章节",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 185,
    "type": "判断题",
    "question": "IE寄存器是8位的。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "待人工复核：IE寄存器为8位宽，包含总中断允许位EA和各中断允许位(ES、ET1、EX1、ET0、EX0等)。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 186,
    "type": "判断题",
    "question": "TR0=1表示定时器T0禁止。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "TR0=1启动定时器0，TR0=0停止定时器0。因此说TR0=1表示禁止是错误的。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "TCON寄存器表",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 187,
    "type": "判断题",
    "question": "外中断0的中断请求标志是IE0。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "IE0是外部中断0的请求标志位，当检测到触发沿时IE0被硬件置1。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "TCON寄存器表",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 188,
    "type": "判断题",
    "question": "1片74HC138有8个输出端。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "74HC138是一片3线至8线译码器，有8个独立输出，选中时输出为低电平。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "74HC138 3-to-8 line decoder",
        "publisher": "On Semiconductor",
        "url": "https://www.onsemi.com/pdf/datasheet/mc74hc138a-d.pdf",
        "documentId": "74HC138",
        "locator": "General description",
        "trust": "official"
      }
    ]
  },
  {
    "id": 189,
    "type": "判断题",
    "question": "TMOD的默认值为0。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 190,
    "type": "判断题",
    "question": "串行通信中，RE代表允许读串行数据。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 191,
    "type": "判断题",
    "question": "IE中ES的含义为允许外中断。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "待人工复核：IE寄存器中的ES位允许或禁止串口中断，与外中断无关，因此说ES允许外中断不正确。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 192,
    "type": "判断题",
    "question": "TMOD用于控制定时器的工作方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "TMOD寄存器用于控制定时器/计数器的工作方式和门控，选择定时或计数功能，因此说TMOD用于控制定时器工作方式正确。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "TMOD寄存器说明",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 193,
    "type": "判断题",
    "question": "外部中断0的中断触发标志位是IT0。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 194,
    "type": "判断题",
    "question": "无源蜂鸣器正常工作时，能发出固定频率的音频信号。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": "未找到权威资料证明该题答案，需要进一步查证。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 195,
    "type": "判断题",
    "question": "外部中断1的中断编号是2。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "待人工复核：中断向量表中外部中断1的向量地址为0013H，对应的中断号为2，因此题目正确。",
    "explanationStatus": "needs_review",
    "explanationConfidence": "low",
    "sources": []
  },
  {
    "id": 196,
    "type": "判断题",
    "question": "74HC138的任意时刻只有1个输出引脚的状态为低电平。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "74HC138译码器在任意时刻只有一个输出为低电平，其余均保持高电平或高阻，这正是译码器的特点。",
    "explanationStatus": "verified",
    "explanationConfidence": "high",
    "sources": [
      {
        "title": "74HC138 3-to-8 line decoder",
        "publisher": "On Semiconductor",
        "url": "https://www.onsemi.com/pdf/datasheet/mc74hc138a-d.pdf",
        "documentId": "74HC138",
        "locator": "General description",
        "trust": "official"
      }
    ]
  },
  {
    "id": 197,
    "type": "判断题",
    "question": "串行口的方式2为多机通信方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "串口模式2专门支持多机通信，提供第九位地址标记，因此题目正确。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "模式2描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 198,
    "type": "判断题",
    "question": "AT89C51单片机可以访问的最大数据存储器空间为64KB。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "MCS-51体系结构提供64KB外部数据存储空间，AT89C51可以通过MOVX指令访问达64KB的数据存储器。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "架构说明",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 199,
    "type": "判断题",
    "question": "基本的通信方式有两种：串行方式和并行通信。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "通信方式可分为串行通信和并行通信两类，这是基本分类。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "串口描述",
        "trust": "authoritative-mirror"
      }
    ]
  },
  {
    "id": 200,
    "type": "判断题",
    "question": "串行口的方式1为双机通信方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": "串口模式1是异步通信模式，适用于点对点(双机)通信，因此题目所述方式1为双机通信方式正确。",
    "explanationStatus": "verified",
    "explanationConfidence": "medium",
    "sources": [
      {
        "title": "80C51 Family Hardware Description",
        "publisher": "Philips",
        "url": "https://www.pjrc.com/tech/8051/80C51_FAM_HARDWARE_1.pdf",
        "documentId": "",
        "locator": "模式1描述",
        "trust": "authoritative-mirror"
      }
    ]
  }
];
