/* Auto-generated by parser.js. Do not edit manually; update questions.txt and rerun `node parser.js`. */
window.QUESTION_BANK = [
  {
    "id": 1,
    "type": "单选题",
    "question": "AT89C51单片机由（ ）个16位定时器/计数器。",
    "options": {
      "A": "3路",
      "B": "2路",
      "C": "1路",
      "D": "4路"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 2,
    "type": "单选题",
    "question": "P3.1口的第二功能是（ ）。",
    "options": {
      "A": "INT1外中断1",
      "B": "RXD 串口输入端",
      "C": "INT0外中断0",
      "D": "TXD串口输出端"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 3,
    "type": "单选题",
    "question": "TH0=N>>8的含义是将（ ）保存到TH0中。",
    "options": {
      "A": "N的高八位",
      "B": "N的十位",
      "C": "N的个位",
      "D": "N的低八位"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 4,
    "type": "单选题",
    "question": "动态显示中，利用74HC138实现片选时，必须确保数码管的类型是（）。",
    "options": {
      "A": "共阴极",
      "B": "共阳极"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 5,
    "type": "单选题",
    "question": "双列直插式封装的AT89C51单片机有（）引脚",
    "options": {
      "A": "40",
      "B": "16",
      "C": "20",
      "D": "32"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 6,
    "type": "单选题",
    "question": "AT89C51单片机定时器T0有（ ）个工作方式。",
    "options": {
      "A": "3",
      "B": "2",
      "C": "1",
      "D": "4"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 7,
    "type": "单选题",
    "question": "外中断0中断服务函数的编号为（ ） 。",
    "options": {
      "A": "3",
      "B": "0",
      "C": "2",
      "D": "1"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 8,
    "type": "单选题",
    "question": "AT89C51单片机在定时器0和外中断0同时申请中断时，CPU首先响应（ ）。",
    "options": {
      "A": "定时器0",
      "B": "外中断0"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 9,
    "type": "单选题",
    "question": "SCON中RI的含义（ ）。",
    "options": {
      "A": "多机通信发送第九位",
      "B": "多机通信接收第九位",
      "C": "接收完毕中断标志",
      "D": "发送完毕中断标志"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 10,
    "type": "单选题",
    "question": "AT89C51单片机可以访问的最大程序存储器空间（ ）。",
    "options": {
      "A": "4KB",
      "B": "64KB",
      "C": "8KB",
      "D": "16KB"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 11,
    "type": "单选题",
    "question": "AT89C51内部提供的T1定时器有（ ）种工作方式。",
    "options": {
      "A": "4",
      "B": "3",
      "C": "1",
      "D": "2"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 12,
    "type": "单选题",
    "question": "P3.0口的第二功能是（ ）。",
    "options": {
      "A": "RXD 串口输入端",
      "B": "INT0外中断0",
      "C": "INT1外中断1",
      "D": "TXD串口输出端"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 13,
    "type": "单选题",
    "question": "串行通信中方式2的波特率是（ ）。",
    "options": {
      "A": "晶振频率/32",
      "B": "晶振频率",
      "C": "晶振频率/16",
      "D": "晶振频率/8"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 14,
    "type": "单选题",
    "question": "串口工作在方式1允许接收，则SCON应该取值为（ ）。",
    "options": {
      "A": "0x90",
      "B": "0x50",
      "C": "0x10",
      "D": "0x00"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 15,
    "type": "单选题",
    "question": "12MHz晶振下，定时器在方式1下最大定时时间为（ ）。",
    "options": {
      "A": "16.384ms",
      "B": "0.256ms",
      "C": "8.192ms",
      "D": "65.536ms"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 16,
    "type": "单选题",
    "question": "SCON中用于保存多机通信接收到的第九位信息的是（ ）。",
    "options": {
      "A": "TI",
      "B": "RI",
      "C": "TB8",
      "D": "RB8"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 17,
    "type": "单选题",
    "question": "单片机是将（ ）做到一块集成电路芯片中，称为单片机。",
    "options": {
      "A": "CPU、RAM",
      "B": "CPU、RAM、ROM",
      "C": "CPU、RAM、ROM、I/O设备",
      "D": "CPU、I/O设备"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 18,
    "type": "单选题",
    "question": "74HC595的MR引脚的功能是（）。",
    "options": {
      "A": "移位时钟端",
      "B": "数据输入端",
      "C": "存储器清零端",
      "D": "锁存端"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 19,
    "type": "单选题",
    "question": "C51中用（ ）符号表示十六进制数字。",
    "options": {
      "A": "0",
      "B": "B",
      "C": "0X",
      "D": "D"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 20,
    "type": "单选题",
    "question": "TCON中TF0代表的含义是（ ）。",
    "options": {
      "A": "定时器T1启动位",
      "B": "定时器T0溢出位",
      "C": "定时器T1溢出位",
      "D": "定时器T0启动位"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 21,
    "type": "单选题",
    "question": "在MCS-51系统中，若晶振频率为6MHz，一个机器周期等于（ ）μs。",
    "options": {
      "A": "2",
      "B": "3",
      "C": "1",
      "D": "4"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 22,
    "type": "单选题",
    "question": "串行通信中的起始位由（ ）电平表示。",
    "options": {
      "A": "高",
      "B": "不确定",
      "C": "高阻",
      "D": "低"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 23,
    "type": "单选题",
    "question": "AT89C51单片机的可靠复位需要在RST引脚产生（）电平？",
    "options": {
      "A": "高",
      "B": "低"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 24,
    "type": "单选题",
    "question": "IE中EA代表的含义是（ ）。",
    "options": {
      "A": "定时器0中断允许",
      "B": "中断允许总控位",
      "C": "定时器1中断允许",
      "D": "串口中断允许"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 25,
    "type": "单选题",
    "question": "定时器T0和T1均工作在方式1，则TMOD需要设置为（ ）。",
    "options": {
      "A": "0X01",
      "B": "0XFF",
      "C": "0X11",
      "D": "0X10"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 26,
    "type": "单选题",
    "question": "P3.2口的第二功能是（ ）。",
    "options": {
      "A": "INT1外中断1",
      "B": "串口输出端",
      "C": "RXD 串口输入端",
      "D": "INT0外中断0"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 27,
    "type": "单选题",
    "question": "已知X的补码为00001000B，则X的真值是十进制（ ）。",
    "options": {
      "A": "-136",
      "B": "-120",
      "C": "8",
      "D": "120"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 28,
    "type": "单选题",
    "question": "SCON中TI的含义（ ）。",
    "options": {
      "A": "多机通信发送第九位",
      "B": "多机通信接收第九位",
      "C": "接收完毕中断标志",
      "D": "发送完毕中断标志"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 29,
    "type": "单选题",
    "question": "AT89C51单片机的（ ）口的引脚，还具有外中断、串行通信等第二功能。",
    "options": {
      "A": "P3",
      "B": "P0",
      "C": "P2",
      "D": "P1"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 30,
    "type": "单选题",
    "question": "AT89C51单片机的工作频率最大为（）",
    "options": {
      "A": "12MHz",
      "B": "48MHz",
      "C": "6MHz",
      "D": "24MHz"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 31,
    "type": "单选题",
    "question": "串行口中断服务函数的编号为（ ） 。",
    "options": {
      "A": "3",
      "B": "2",
      "C": "4",
      "D": "1"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 32,
    "type": "单选题",
    "question": "在16*16点阵显示中，逐行扫描的频率最小为（）Hz？",
    "options": {
      "A": "8*24",
      "B": "32*24",
      "C": "24",
      "D": "16*24"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 33,
    "type": "单选题",
    "question": "要设计一个32键的行列式键盘，至少需要占用（ ）根引脚线。",
    "options": {
      "A": "无法确定",
      "B": "12",
      "C": "18",
      "D": "32"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 34,
    "type": "单选题",
    "question": "AT89C51单片机串口可以工作（ ）模式下。",
    "options": {
      "A": "单工通信",
      "B": "半双工通信",
      "C": "不确定",
      "D": "全双工通信"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 35,
    "type": "单选题",
    "question": "AT89C51单片机对内部脉冲计数实现的是（ ）功能。",
    "options": {
      "A": "计数器",
      "B": "定时器"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 36,
    "type": "单选题",
    "question": "sbit 用于声明（）变量？",
    "options": {
      "A": "字符",
      "B": "特殊功能寄存器的位",
      "C": "实型",
      "D": "整形"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 37,
    "type": "单选题",
    "question": "P3.3口的第二功能是（ ）。",
    "options": {
      "A": "INT0外中断0",
      "B": "TXD串口输出端",
      "C": "INT1外中断1",
      "D": "RXD 串口输入端"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 38,
    "type": "单选题",
    "question": "SCON中SM0，SM1取00代表的含义是串行工作方式（ ）。",
    "options": {
      "A": "工作方式1",
      "B": "工作方式2",
      "C": "工作方式0",
      "D": "工作方式3"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 39,
    "type": "单选题",
    "question": "74HC595的OE引脚的功能是（）。",
    "options": {
      "A": "存储器清零端",
      "B": "输出使能端",
      "C": "锁存端",
      "D": "数据输入端"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 40,
    "type": "单选题",
    "question": "bit 用于声明（）类型的变量？",
    "options": {
      "A": "实型",
      "B": "字符",
      "C": "整形",
      "D": "位"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 41,
    "type": "单选题",
    "question": "AT89C51单片机具有第二功能引脚的端口是（ ）。",
    "options": {
      "A": "P1",
      "B": "P2",
      "C": "P0",
      "D": "P3"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 42,
    "type": "单选题",
    "question": "串行通信中的停止位由（ ）电平标示。",
    "options": {
      "A": "高",
      "B": "不确定",
      "C": "低",
      "D": "高阻"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 43,
    "type": "单选题",
    "question": "C51中用（ ）符号表示八进制数字。",
    "options": {
      "A": "0X",
      "B": "D",
      "C": "B",
      "D": "O"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 44,
    "type": "单选题",
    "question": "欲使P1口的低4位输出0，高4位不变，应执行一条（ ）命令。",
    "options": {
      "A": "P1&=0X0F",
      "B": "P1&=0XF0",
      "C": "P1=0XF0",
      "D": "P1=0X0F"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 45,
    "type": "单选题",
    "question": "IE中EX0代表的含义是允许（ ）中断。",
    "options": {
      "A": "定时器T0",
      "B": "外中断0",
      "C": "外中断1",
      "D": "定时器T1"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 46,
    "type": "单选题",
    "question": "外中断1中断服务函数的编号为（ ） 。",
    "options": {
      "A": "4",
      "B": "1",
      "C": "2",
      "D": "3"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 47,
    "type": "单选题",
    "question": "TCON中IE0代表的含义是（ ）。",
    "options": {
      "A": "外中断0请求标志",
      "B": "外中断1触发控制位",
      "C": "外中断0触发控制位",
      "D": "外中断1请求标志"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 48,
    "type": "单选题",
    "question": "串行通信中方式1的功能是（ ）。",
    "options": {
      "A": "固定频率9位通信",
      "B": "同步移位寄存器方式",
      "C": "8位异步通信",
      "D": "可变频率9位通信"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 49,
    "type": "单选题",
    "question": "串行通信中的空闲信号由（ ）电平标示。",
    "options": {
      "A": "低",
      "B": "高阻",
      "C": "不确定",
      "D": "高"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 50,
    "type": "单选题",
    "question": "通常一个16*16点阵汉字需要（）字节保存？",
    "options": {
      "A": "8",
      "B": "64",
      "C": "16",
      "D": "32"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 51,
    "type": "单选题",
    "question": "开启定时器0时TR0的值应该设置为（ ）。",
    "options": {
      "A": "OXFF",
      "B": "0",
      "C": "1",
      "D": "-1"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 52,
    "type": "单选题",
    "question": "打开定时器T0和T1中断，需要设置IE为（ ）。",
    "options": {
      "A": "0X8A",
      "B": "0X80",
      "C": "0X82",
      "D": "0X88"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 53,
    "type": "单选题",
    "question": "定时方式1是（ )位二进制定时。",
    "options": {
      "A": "8",
      "B": "13",
      "C": "16",
      "D": "32"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 54,
    "type": "单选题",
    "question": "AT89C51单片机有（ ）个端口。",
    "options": {
      "A": "3",
      "B": "1",
      "C": "4",
      "D": "2"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 55,
    "type": "单选题",
    "question": "当允许定时器1工作在方式1时，控制字TMOD应为（ ）。",
    "options": {
      "A": "0X01",
      "B": "0XFF",
      "C": "0X11",
      "D": "0X10"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 56,
    "type": "单选题",
    "question": "定时/计数器T1的溢出标志位是（ ）。",
    "options": {
      "A": "IE1",
      "B": "TF1",
      "C": "IT1",
      "D": "ET1"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 57,
    "type": "单选题",
    "question": "串行通信中方式0的功能是（ ）。",
    "options": {
      "A": "可变频率9位通信",
      "B": "固定频率9位通信",
      "C": "同步移位寄存器方式",
      "D": "8位异步通信"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 58,
    "type": "单选题",
    "question": "AT89C51是（ ）位的单片机。",
    "options": {
      "A": "8",
      "B": "32",
      "C": "16",
      "D": "4"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 59,
    "type": "单选题",
    "question": "定时器默认的内部时钟源是振荡器信号的（ )分频。",
    "options": {
      "A": "16",
      "B": "4",
      "C": "12",
      "D": "8"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 60,
    "type": "单选题",
    "question": "在异步通信中若每个字符由10位组成，串行口波特率为4800bps，则每秒传送字符数最多为（ ）。",
    "options": {
      "A": "120",
      "B": "960",
      "C": "480",
      "D": "240"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 61,
    "type": "单选题",
    "question": "开机时，TR0的默认值是（ ）。",
    "options": {
      "A": "OXFF",
      "B": "1",
      "C": "-1",
      "D": "0"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 62,
    "type": "单选题",
    "question": "中断使能寄存器IE中ES代表的含义是（ ）。",
    "options": {
      "A": "中断允许总控位",
      "B": "定时器0中断允许",
      "C": "串口中断允许",
      "D": "定时器1中断允许"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 63,
    "type": "单选题",
    "question": "74HC595的SH_CP引脚的功能是（）。",
    "options": {
      "A": "锁存端",
      "B": "片选信号",
      "C": "移位时钟端",
      "D": "数据输入端"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 64,
    "type": "单选题",
    "question": "74HC595的ST_CP引脚的功能是（）。",
    "options": {
      "A": "数据输入端",
      "B": "片选信号",
      "C": "锁存端",
      "D": "移位时钟端"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 65,
    "type": "单选题",
    "question": "T1中断服务函数的编号为（ ） 。",
    "options": {
      "A": "3",
      "B": "2",
      "C": "1",
      "D": "4"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 66,
    "type": "单选题",
    "question": "AT89C51单片机定时器采用的是（ ）计数方式。",
    "options": {
      "A": "不确定",
      "B": "减计数",
      "C": "加或减计数",
      "D": "加计数"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 67,
    "type": "单选题",
    "question": "若振荡频率为12MHz，在方式2下最大定时时间为（ ）。",
    "options": {
      "A": "65.536ms",
      "B": "8.192ms",
      "C": "16.384ms",
      "D": "0.256ms"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 68,
    "type": "单选题",
    "question": "控制串形接口工作方式的寄存器是（ ）。",
    "options": {
      "A": "PCON",
      "B": "TMOD",
      "C": "TCON",
      "D": "SCON"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 69,
    "type": "单选题",
    "question": "串行通信中方式2的功能是（ ）。",
    "options": {
      "A": "固定频率9位通信",
      "B": "8位异步通信",
      "C": "可变频率9位通信",
      "D": "同步移位寄存器方式"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 70,
    "type": "单选题",
    "question": "ADC0809的转换速率主要取决于（）。",
    "options": {
      "A": "启动信号",
      "B": "参考电压",
      "C": "供电电压",
      "D": "工作频率的大小"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 71,
    "type": "单选题",
    "question": "下面（ ）种方式适合用于处理外部突发事件。",
    "options": {
      "A": "DMA",
      "B": "条件查询传送",
      "C": "中断",
      "D": "无条件传送"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 72,
    "type": "单选题",
    "question": "74HC138的A、B、C引脚的作用是（）。",
    "options": {
      "A": "使能",
      "B": "复位",
      "C": "改变输出引脚的状态"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 73,
    "type": "单选题",
    "question": "AT89C51单片机串口的工作方式有（ ）种。",
    "options": {
      "A": "2",
      "B": "3",
      "C": "1",
      "D": "4"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 74,
    "type": "单选题",
    "question": "1个16*16点阵可以由（）个8*8点阵实现？",
    "options": {
      "A": "3",
      "B": "4",
      "C": "1",
      "D": "2"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 75,
    "type": "单选题",
    "question": "SCON中SM2用于方式（ ）。",
    "options": {
      "A": "工作方式1",
      "B": "仅在工作方式3中",
      "C": "工作方式2和3",
      "D": "工作方式0"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 76,
    "type": "单选题",
    "question": "串行通信中方式3的功能是（ ）。",
    "options": {
      "A": "可变频率9位通信",
      "B": "8位异步通信",
      "C": "同步移位寄存器方式",
      "D": "固定频率9位通信"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 77,
    "type": "单选题",
    "question": "74HC595的DS引脚的功能是（）。",
    "options": {
      "A": "移位时钟端",
      "B": "片选信号",
      "C": "数据输入端",
      "D": "锁存端"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 78,
    "type": "单选题",
    "question": "IE中EX1代表的含义是允许（ ）中断。",
    "options": {
      "A": "定时器T1",
      "B": "定时器T0",
      "C": "外中断1",
      "D": "外冲断0"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 79,
    "type": "单选题",
    "question": "CPU又称为（）",
    "options": {
      "A": "控制器",
      "B": "输入/输出设备",
      "C": "运算器",
      "D": "中央处理器"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 80,
    "type": "单选题",
    "question": "AT89C51复位时,下述说法正确的是（ ）。",
    "options": {
      "A": "SP=00H",
      "B": "P0=00H",
      "C": "SBUF=00H",
      "D": "TH0=00H"
    },
    "answer": "D",
    "explanation": ""
  },
  {
    "id": 81,
    "type": "单选题",
    "question": "当采用12MHz晶振时，定时器的工作时钟周期为（）μs。",
    "options": {
      "A": "0.5",
      "B": "2",
      "C": "1",
      "D": "3"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 82,
    "type": "单选题",
    "question": "设计一个16键的矩阵式键盘，至少需要占用（ ）IO引脚。",
    "options": {
      "A": "2",
      "B": "6",
      "C": "8",
      "D": "4"
    },
    "answer": "C",
    "explanation": ""
  },
  {
    "id": 83,
    "type": "多选题",
    "question": "电子时钟项目中包括（）模块",
    "options": {
      "A": "数码管显示模块",
      "B": "按键",
      "C": "点阵模块",
      "D": "74595"
    },
    "answer": "ABD",
    "explanation": ""
  },
  {
    "id": 84,
    "type": "多选题",
    "question": "一般常用（）显示字符点阵，而用（）显示汉字点阵",
    "options": {
      "A": "32*32",
      "B": "16*16",
      "C": "8*8"
    },
    "answer": "BC",
    "explanation": ""
  },
  {
    "id": 85,
    "type": "多选题",
    "question": "A/D转换后的结果可以采用（）方法采集。",
    "options": {
      "A": "查询",
      "B": "中断",
      "C": "延时"
    },
    "answer": "ABC",
    "explanation": ""
  },
  {
    "id": 86,
    "type": "多选题",
    "question": "定时器/计数器T1有（ ）3种工作方式。",
    "options": {
      "A": "方式3",
      "B": "方式0",
      "C": "方式1",
      "D": "方式2"
    },
    "answer": "BCD",
    "explanation": ""
  },
  {
    "id": 87,
    "type": "多选题",
    "question": "AT89C51单片机最小系统包括（）",
    "options": {
      "A": "电源电路",
      "B": "数码管显示电路",
      "C": "时钟电路",
      "D": "复位电路"
    },
    "answer": "ACD",
    "explanation": ""
  },
  {
    "id": 88,
    "type": "多选题",
    "question": "超声波身高检测系统中包括（）模块",
    "options": {
      "A": "语音模块",
      "B": "矩阵式按键",
      "C": "串行口通信",
      "D": "超声波模块"
    },
    "answer": "ACD",
    "explanation": ""
  },
  {
    "id": 89,
    "type": "多选题",
    "question": "数码管按照公共端的不同可以分为（）类型",
    "options": {
      "A": "共阴极",
      "B": "动态显示",
      "C": "静态显示",
      "D": "共阳极"
    },
    "answer": "AD",
    "explanation": ""
  },
  {
    "id": 90,
    "type": "多选题",
    "question": "利用单片机实现电子琴的设计时，可采用（）来发声",
    "options": {
      "A": "麦克风",
      "B": "有源蜂鸣器",
      "C": "扬声器",
      "D": "无源蜂鸣器"
    },
    "answer": "CD",
    "explanation": ""
  },
  {
    "id": 91,
    "type": "多选题",
    "question": "利用定时器可以实现（）功能",
    "options": {
      "A": "产生方波",
      "B": "计数",
      "C": "延时",
      "D": "定时"
    },
    "answer": "ABCD",
    "explanation": ""
  },
  {
    "id": 92,
    "type": "多选题",
    "question": "驱动数码管动态显示的芯片可以采用（）",
    "options": {
      "A": "74595",
      "B": "74161",
      "C": "7447",
      "D": "74138"
    },
    "answer": "ACD",
    "explanation": ""
  },
  {
    "id": 93,
    "type": "多选题",
    "question": "AT89C51的并行端口作输入口时，必须先写（ ） 才能读入外设的状态。",
    "options": {
      "A": "0",
      "B": "低电平",
      "C": "1",
      "D": "高电平"
    },
    "answer": "CD",
    "explanation": ""
  },
  {
    "id": 94,
    "type": "多选题",
    "question": "能够触发定时中断的信号有（）",
    "options": {
      "A": "TF1",
      "B": "TI",
      "C": "TF0",
      "D": "RI"
    },
    "answer": "AC",
    "explanation": ""
  },
  {
    "id": 95,
    "type": "多选题",
    "question": "关于ADC0809的描述正确的是（）",
    "options": {
      "A": "8个输出输出端",
      "B": "3个通道选择端",
      "C": "8个数据输入端",
      "D": "1个频率信号输入端"
    },
    "answer": "ABCD",
    "explanation": ""
  },
  {
    "id": 96,
    "type": "多选题",
    "question": "在工程设计中，定时器T0常用作（），定时T1常用作（）。",
    "options": {
      "A": "定时",
      "B": "计数",
      "C": "延时",
      "D": "波特率发生"
    },
    "answer": "AD",
    "explanation": ""
  },
  {
    "id": 97,
    "type": "多选题",
    "question": "能够触发串行口中断的信号包括（）",
    "options": {
      "A": "EX0",
      "B": "TI",
      "C": "EX1",
      "D": "RI"
    },
    "answer": "BD",
    "explanation": ""
  },
  {
    "id": 98,
    "type": "多选题",
    "question": "AT89C51的堆栈存取数据的原则是（ ）。",
    "options": {
      "A": "先进后出",
      "B": "后进先出",
      "C": "先进先出",
      "D": "后进后出"
    },
    "answer": "AB",
    "explanation": ""
  },
  {
    "id": 99,
    "type": "多选题",
    "question": "AT89C51单片机的中断源分别有外部中断0（ ）。",
    "options": {
      "A": "T1",
      "B": "外部中断1",
      "C": "串行口",
      "D": "T0"
    },
    "answer": "ABCD",
    "explanation": ""
  },
  {
    "id": 100,
    "type": "多选题",
    "question": "虽然ADC0809有（）数据输入端，但是某一刻只有（）引脚起作用",
    "options": {
      "A": "4",
      "B": "1",
      "C": "2",
      "D": "8"
    },
    "answer": "BD",
    "explanation": ""
  },
  {
    "id": 101,
    "type": "多选题",
    "question": "常用的延时方法包括（）",
    "options": {
      "A": "定时器延时",
      "B": "软件延时"
    },
    "answer": "AB",
    "explanation": ""
  },
  {
    "id": 102,
    "type": "多选题",
    "question": "独立按键扫描方法包括（）",
    "options": {
      "A": "反转法",
      "B": "扫描法",
      "C": "延时等待法",
      "D": "键标志法"
    },
    "answer": "CD",
    "explanation": ""
  },
  {
    "id": 103,
    "type": "多选题",
    "question": "常见的波特率包括（）",
    "options": {
      "A": "2400",
      "B": "1200",
      "C": "4800",
      "D": "9600"
    },
    "answer": "ABCD",
    "explanation": ""
  },
  {
    "id": 104,
    "type": "多选题",
    "question": "AT89C51单片机可以处理的中断包括（）",
    "options": {
      "A": "外中断",
      "B": "串行口中断",
      "C": "看门狗中断",
      "D": "定时器中断"
    },
    "answer": "ABD",
    "explanation": ""
  },
  {
    "id": 105,
    "type": "多选题",
    "question": "与状态相关参数有（）。",
    "options": {
      "A": "触发信号",
      "B": "响应信号",
      "C": "状态圆圈",
      "D": "状态转移线"
    },
    "answer": "ABCD",
    "explanation": ""
  },
  {
    "id": 106,
    "type": "多选题",
    "question": "单片机控制系统中，常见的按键包括（）",
    "options": {
      "A": "矩阵式按键",
      "B": "轻触开关",
      "C": "旋钮开关",
      "D": "拨码开关"
    },
    "answer": "ABCD",
    "explanation": ""
  },
  {
    "id": 107,
    "type": "多选题",
    "question": "无源蜂鸣器的特点是（）",
    "options": {
      "A": "两个引脚长度相同",
      "B": "外加电源后还需要加音源才能发声",
      "C": "外加电源后可直接发声",
      "D": "两个引脚长度不同"
    },
    "answer": "AB",
    "explanation": ""
  },
  {
    "id": 108,
    "type": "多选题",
    "question": "计算器项目中包括（）模块",
    "options": {
      "A": "超声波模块",
      "B": "数码管",
      "C": "单片机",
      "D": "按键"
    },
    "answer": "BCD",
    "explanation": ""
  },
  {
    "id": 109,
    "type": "多选题",
    "question": "串行通信的数据传送方式可以是（ ）。",
    "options": {
      "A": "全双工",
      "B": "双工",
      "C": "半双工",
      "D": "单工"
    },
    "answer": "ACD",
    "explanation": ""
  },
  {
    "id": 110,
    "type": "多选题",
    "question": "按键在与IO相连时一般需要连接（）电阻",
    "options": {
      "A": "下拉",
      "B": "限流",
      "C": "上拉"
    },
    "answer": "AC",
    "explanation": ""
  },
  {
    "id": 111,
    "type": "多选题",
    "question": "可利用串行口进行通信的设备包括（）",
    "options": {
      "A": "语音模块",
      "B": "超声波模块",
      "C": "GPS模块",
      "D": "GSM模块"
    },
    "answer": "ABCD",
    "explanation": ""
  },
  {
    "id": 112,
    "type": "多选题",
    "question": "异步串行数据通信的帧格式一般由（ ）组成。",
    "options": {
      "A": "停止位",
      "B": "校验位",
      "C": "起始位",
      "D": "数据位"
    },
    "answer": "ABCD",
    "explanation": ""
  },
  {
    "id": 113,
    "type": "多选题",
    "question": "AT89C51单片机的外中断触发方式控制位包括（ ）。",
    "options": {
      "A": "IT0",
      "B": "IE0",
      "C": "TI1",
      "D": "IE1"
    },
    "answer": "AC",
    "explanation": ""
  },
  {
    "id": 114,
    "type": "多选题",
    "question": "与定时器相关的寄存器包括（）",
    "options": {
      "A": "TRx",
      "B": "TCON",
      "C": "IE",
      "D": "TMOD"
    },
    "answer": "ABCD",
    "explanation": ""
  },
  {
    "id": 115,
    "type": "多选题",
    "question": "计算机中常用于表达数值的码制有（ ）。",
    "options": {
      "A": "反码",
      "B": "原码",
      "C": "补码"
    },
    "answer": "ABC",
    "explanation": ""
  },
  {
    "id": 116,
    "type": "多选题",
    "question": "74hc595可以用于驱动（）",
    "options": {
      "A": "蜂鸣器",
      "B": "点阵",
      "C": "继电器",
      "D": "数码管"
    },
    "answer": "BD",
    "explanation": ""
  },
  {
    "id": 117,
    "type": "多选题",
    "question": "合法的中断服务函数的编号为（ ） 。",
    "options": {
      "A": "2",
      "B": "3",
      "C": "1",
      "D": "0"
    },
    "answer": "ABCD",
    "explanation": ""
  },
  {
    "id": 118,
    "type": "多选题",
    "question": "常用的数码管显示方式包括（）",
    "options": {
      "A": "动态显示",
      "B": "静态显示",
      "C": "动静结合"
    },
    "answer": "AB",
    "explanation": ""
  },
  {
    "id": 119,
    "type": "多选题",
    "question": "中断控制器（）中，EA代表的是开总中断，ET0代表（），EX0代表（）",
    "options": {
      "A": "外中断0允许",
      "B": "IE",
      "C": "定时器0中断允许",
      "D": "定时器1中断允许"
    },
    "answer": "ABC",
    "explanation": ""
  },
  {
    "id": 120,
    "type": "多选题",
    "question": "串行口方式0又称为（）方式，方式1称为（）方式，方式2-3称为（）方式",
    "options": {
      "A": "异步通信",
      "B": "移位寄存器",
      "C": "双机通信",
      "D": "多机通信"
    },
    "answer": "BCD",
    "explanation": ""
  },
  {
    "id": 121,
    "type": "多选题",
    "question": "AT89C51一直维持复位状态，直到RST脚收到（ ）电平，MCS-51才脱离复位状态，进入程序运行状态。",
    "options": {
      "A": "0",
      "B": "低",
      "C": "1",
      "D": "高"
    },
    "answer": "AB",
    "explanation": ""
  },
  {
    "id": 122,
    "type": "多选题",
    "question": "AT89C51内部提供的T0定时器有（ ）种工作方式。",
    "options": {
      "A": "方式0",
      "B": "方式3",
      "C": "方式2",
      "D": "方式1"
    },
    "answer": "ABCD",
    "explanation": ""
  },
  {
    "id": 123,
    "type": "多选题",
    "question": "下列属于输出设备的是（）",
    "options": {
      "A": "继电器",
      "B": "矩阵式按键",
      "C": "蜂鸣器",
      "D": "可控硅"
    },
    "answer": "ACD",
    "explanation": ""
  },
  {
    "id": 124,
    "type": "多选题",
    "question": "矩阵式按键主要应用场合是（）",
    "options": {
      "A": "按键少",
      "B": "IO口资源紧张",
      "C": "按键较多",
      "D": "IO口资源丰富"
    },
    "answer": "BC",
    "explanation": ""
  },
  {
    "id": 125,
    "type": "多选题",
    "question": "AT89C51单片机的内部硬件结构包括（ ）。",
    "options": {
      "A": "中断控制系统",
      "B": "ROM",
      "C": "定时器",
      "D": "串行口"
    },
    "answer": "ABCD",
    "explanation": ""
  },
  {
    "id": 126,
    "type": "判断题",
    "question": "有源蜂鸣器的两个引脚是等长的。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 127,
    "type": "判断题",
    "question": "串行口收发数据缓存器的名字为SBUF。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 128,
    "type": "判断题",
    "question": "AT89C51单片机的外中断常工作在下降沿触发模式下。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 129,
    "type": "判断题",
    "question": "TCON中TF1代表的含义是定时器溢出标志。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 130,
    "type": "判断题",
    "question": "串行口的方式0也称为移位寄存器方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 131,
    "type": "判断题",
    "question": "在串行通信中,数据传送方向单工、半双工、全双工三种方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 132,
    "type": "判断题",
    "question": "串行口发生中断时RI或TI至少有一个为1态。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 133,
    "type": "判断题",
    "question": "开启定时器T0中断时，应设置IE=0X02。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 134,
    "type": "判断题",
    "question": "AT89C51中断优先级由寄存器IP来决定。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 135,
    "type": "判断题",
    "question": "开机复位后，每个端口的状态为0。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 136,
    "type": "判断题",
    "question": "有源蜂鸣器的引脚的极性为长正短负。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 137,
    "type": "判断题",
    "question": "中断服务函数中 interrupt 1指的是T0中断的服务函数。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 138,
    "type": "判断题",
    "question": "外部中断1的中断触发标志位是IT0。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 139,
    "type": "判断题",
    "question": "超声波模块可以工作在串行口模式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 140,
    "type": "判断题",
    "question": "外部中断1的输入引脚是P3.2。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 141,
    "type": "判断题",
    "question": "定时器T1还可以用作串行口波特率发生器使用。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 142,
    "type": "判断题",
    "question": "启动定时器T0应该使用TR0=1。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 143,
    "type": "判断题",
    "question": "无源蜂鸣器的两个引脚是等长的。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 144,
    "type": "判断题",
    "question": "独立按键识别时，先延时再判断的目的是避开按键抖动。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 145,
    "type": "判断题",
    "question": "AT89C51内部提供2个可编程的16位定时/计数器，T0定时器有3种工作方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 146,
    "type": "判断题",
    "question": "ADC0809内部有8个电压转换模块。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 147,
    "type": "判断题",
    "question": "P3.3的第二功能为外中断1的输入端。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 148,
    "type": "判断题",
    "question": "IE中ET1的含义为允许定时器1中断。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 149,
    "type": "判断题",
    "question": "MCS-51单片机的外中断可以工作在低电平触发或者下降沿触发模式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 150,
    "type": "判断题",
    "question": "P3.2的第二功能为外中断0的输入端。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 151,
    "type": "判断题",
    "question": "若使用T0中断，则只需要设置ET0=1即可。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 152,
    "type": "判断题",
    "question": "串行口中断结束后RI由硬件自动清零。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 153,
    "type": "判断题",
    "question": "74HC595芯片的功能是数据锁存。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 154,
    "type": "判断题",
    "question": "8位有符号数的范围为-128~127。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 155,
    "type": "判断题",
    "question": "AT89C51的中断源全部编程为同级时，优先级最低的是外中断0。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 156,
    "type": "判断题",
    "question": "定时器T0工作在方式1下，采用定时功能，门控位不使用，则TMOD=1。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 157,
    "type": "判断题",
    "question": "ADC0809的转换精度为参考电压Vref/256。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 158,
    "type": "判断题",
    "question": "LED常采用灌电流的驱动方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 159,
    "type": "判断题",
    "question": "外部中断1的中断请求标志位是TF1。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 160,
    "type": "判断题",
    "question": "IP的默认值为0。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 161,
    "type": "判断题",
    "question": "IT1=1表示外部中断1的触发方式为边沿触发。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 162,
    "type": "判断题",
    "question": "矩阵式按键扫描常用的方法有翻转法和扫描法。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 163,
    "type": "判断题",
    "question": "MCS-51内部有4个并行IO口。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 164,
    "type": "判断题",
    "question": "数码管动态显示利用了视觉暂留效应。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 165,
    "type": "判断题",
    "question": "SCON中SM0,SM1取01代表的含义是串行工作方式1。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 166,
    "type": "判断题",
    "question": "定时器T1的方式1常用于串行口波特率发生器使用。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 167,
    "type": "判断题",
    "question": "无符号字节型变量的表达范围是0~255。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 168,
    "type": "判断题",
    "question": "CPU的运算器可以完成算数运算和逻辑运算。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 169,
    "type": "判断题",
    "question": "89的补码用8位二进制数表示是01011001B。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 170,
    "type": "判断题",
    "question": "SM2用于多机通信方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 171,
    "type": "判断题",
    "question": "AT89C51有5个中断源。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 172,
    "type": "判断题",
    "question": "MCS-51单片机的CPU是8位的。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 173,
    "type": "判断题",
    "question": "串行口的方式2和3为多机通信波特率可变的方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 174,
    "type": "判断题",
    "question": "设置串口的波特率加倍，则SMOD需要设置为1。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 175,
    "type": "判断题",
    "question": "复位后TMOD的状态为0。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 176,
    "type": "判断题",
    "question": "ADC0809的参考电压可以与单片机的电源电压不同。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 177,
    "type": "判断题",
    "question": "串行通信中，RI用于表达数据传输是否结束。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 178,
    "type": "判断题",
    "question": "定时/计数器T0的中断编号是3。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 179,
    "type": "判断题",
    "question": "TMOD是中断允许寄存器。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 180,
    "type": "判断题",
    "question": "AT89C51单片机的串行口有4种工作方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 181,
    "type": "判断题",
    "question": "外部中断0的输入引脚是P3.2。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 182,
    "type": "判断题",
    "question": "SMOD位于PCON的最高位。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 183,
    "type": "判断题",
    "question": "计算机中补码常用于表达有符号数。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 184,
    "type": "判断题",
    "question": "AT89C51单片机定时器采用的是减计数方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 185,
    "type": "判断题",
    "question": "IE寄存器是8位的。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 186,
    "type": "判断题",
    "question": "TR0=1表示定时器T0禁止。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 187,
    "type": "判断题",
    "question": "外中断0的中断请求标志是IE0。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 188,
    "type": "判断题",
    "question": "1片74HC138有8个输出端。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 189,
    "type": "判断题",
    "question": "TMOD的默认值为0。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 190,
    "type": "判断题",
    "question": "串行通信中，RE代表允许读串行数据。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 191,
    "type": "判断题",
    "question": "IE中ES的含义为允许外中断。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 192,
    "type": "判断题",
    "question": "TMOD用于控制定时器的工作方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 193,
    "type": "判断题",
    "question": "外部中断0的中断触发标志位是IT0。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 194,
    "type": "判断题",
    "question": "无源蜂鸣器正常工作时，能发出固定频率的音频信号。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "B",
    "explanation": ""
  },
  {
    "id": 195,
    "type": "判断题",
    "question": "外部中断1的中断编号是2。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 196,
    "type": "判断题",
    "question": "74HC138的任意时刻只有1个输出引脚的状态为低电平。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 197,
    "type": "判断题",
    "question": "串行口的方式2为多机通信方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 198,
    "type": "判断题",
    "question": "AT89C51单片机可以访问的最大数据存储器空间为64KB。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 199,
    "type": "判断题",
    "question": "基本的通信方式有两种：串行方式和并行通信。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  },
  {
    "id": 200,
    "type": "判断题",
    "question": "串行口的方式1为双机通信方式。",
    "options": {
      "A": "对",
      "B": "错"
    },
    "answer": "A",
    "explanation": ""
  }
];
